### ISSUE TITLE
Explanation of nested array of uneeded-tc-list

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#103]
This is not an issue, just the explanation of https://github.com/ietf-teep/teep-protocol/pull/102

The type of unneeded-tc-list in query-response and update is following,
```
? unneeded-tc-list => [ + SUIT_Component_Identifier ],
```
so it could describe multiple TCs by using array.
At the same time, the type of SUIT_Component_Identifier is defined in https://tools.ietf.org/html/draft-moran-suit-manifest-05 as 
```
SUIT_Component_Identifier =  [* bstr]
```
to contain description of one TC in array, in the way of https://github.com/suit-wg/manifest-spec/blob/master/draft-ietf-suit-manifest.md#SUIT_Component_Identifier-suit-component-identifier as
```
A Component Identifier can be trivial, such as the simple array [h'00']. It can also represent a filesystem path by encoding each segment of the path as an element in the list. For example, the path "/usr/bin/env" would encode to ['usr','bin','env'].
```
which require to be an array to specify one TC.

Therefore, `[ + SUIT_Component_Identifier ]` will be nested array in binary representation as following example.
```
    81                   # array(1)
      81                 # array(1)
        4F               # bytes(15)
          0102030405060708090A0B0C0D0E0F
```
https://github.com/hisanak Thanks for pointing this out.

**Comment by mcd500** [comment]
@dthaler do you mind reviewing the PR?

**Comment by mcd500** [comment]
https://github.com/ietf-teep/teep-protocol/pull/102 is merged. @dthaler Thanks.

**Comment by dthaler** [comment]
Fixed in draft -05
