### ISSUE TITLE
Construction of SUIT_Envelope of URI outside the digest region

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#105]
This is related https://github.com/ietf-teep/teep-protocol/issues/104, but more on how the SUIT_Envelope is constructed.

This is a question when we were thinking how to make the uri changeable.
By reading the section 5.5 of the suit-manifest, it may be possible to change the uri inside suit-install in the SUIT_Envelope with "Severed" feature.
https://tools.ietf.org/html/draft-ietf-suit-manifest-11#section-5.5

The following are the two examples of adding Severed suit-install by TAM.

This is the first idea that came up.
```
SUIT_Envelope = {
 suit-authentication-wrapper : {
   [
     / algorithm-id / 2 / "sha256" /,
     / digest-bytes / h'(digest-of-suit-manifest)'
   ]
 },
 suit-manifest : {
   suit-common : {
   },
   suit-install : {
     directive-set-parameters : {
       uri : 'http://example.com/original_tc_signed'
     }
   }
 },
 // TAM can add Severed suit-install, but the device cannot verify the 
TC binary whether the TC binary is authentic created by TC signer because 
there is no digest information of the TC binary.
 suit-install : {
   suit-directive-set-parameters : {
     uri : 'http://example.com/a_not_tc_signed'
   },
 }
}
```

Adding digest of the TC binary to be able to verify the authenticity of the TC binary.
```
SUIT_Envelope = {
 suit-authentication-wrapper : {
   [
     / algorithm-id / 2 / "sha256" /,
     / digest-bytes / h'(digest-of-suit-manifest)'
   ]
 },
 suit-manifest : {
   suit-common : {
   },
   suit-install : {
     directive-set-parameters : {
       uri : 'http://example.com/original_tc_signed',
       image-digest : [
         / algorithm-id / 2 / "sha256",
         / digest-bytes / h'(digest-of-image)'
       ]
     }
   }
 },
 // TAM adding Severed suit-install. The device can verify whether the 
TC binary image downloaded from the uri added by TAM  is an 
authentic binary created by TC signer with the image-digest in the 
signed area of the SUIT_Envelope.
 suit-install : {
   suit-directive-set-parameters : {
     uri : 'http://example.com/a_not_tc_signed'
   },
 }
}
```

I would like to propose the second example to be legimite for the TEEP usage.
Would be OK?

**Comment by hisanak** [comment]
How about this one? Mimicking example 2 in suit-manifest, this example allows the TAM to change the distribution uri freely.
The points are:
1. severs suit-install containing distribution uri
1. doesn't set the digest of the severed element (suit-install) to change the distribution uri
1. clarifys that the firmware author delegates device operator to decide distribution uri by setting uri = Null in suit-common-sequence (this requires type change suit-manifest change)
```
SUIT_Envelope = {
  / manifest / 3:bstr .cbor ({
    / common / 3:bstr .cbor ({
      / components / 2:[
        [h'00']
      ],
      / common-sequence / 4:bstr .cbor ([
        / directive-set-parameters / 19,{
          / uri / 21:Null / Points#3. Clarify the uri will be overridden below (in severed suit-install). /,
        },
        / directive-override-parameters / 20,{
          / image-digest / 3:bstr .cbor ([
            / algorithm-id / 2 / "sha256" /,
            / digest-bytes / h'(digest of image)'
          ]),
          / image-size / 14:34768
        }
      ])
    }),
    / install / 9:[] / Points#2. The digest of severed suit-install SHOULD NOT be set in order to change the uri by TAM's will. /
  }),
  / install / 9:bstr .cbor ([ / Points#1. TAM CAN change severed and not digested suit-install. /
    / directive-override-parameters / 20,{
      / uri / 21:'http://set.by.not.author.but.tam/firmware',
    }
  }
}
```

**Comment by dthaler** [comment]
@bremoran this looks like more of a comment/question on the SUIT manifest draft rather than the TEEP protocol spec

**Comment by mcd500** [comment]
@bremoran @dthaler let's discuss this at IETF 110 TEEP session, since this is use-cases of SUIT manifest in TEEP

**Comment by mcd500** [comment]
Fixed in https://github.com/ietf-teep/teep-protocol/pull/161/
