### ISSUE TITLE
RequestPolicyCheck API and multiple TAMs

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#111]
Now that #87 is merged, https://github.com/ietf-teep/otrp-over-http/issues/32 now applies to the protocol doc as well.

As shown in Figure 1 of the TEEP architecture doc, a TEEP Agent may need to talk to multiple TAMs (e.g., one to get a TA, and a second one to get personalization data).

The TEEP protocol spec currently says:

> When the RequestPolicyCheck API is invoked, the TEEP Agent decides
> whether to initiate communication with any trusted TAMs (e.g., it might
> choose to do so for a given TAM unless it detects that it has already
> communicated with that TAM recently). If so, it passes back a TAM URI
> to connect to.

The question is if the API can only pass back "a" TAM URI, then how does it conduct policy checks with multiple TAMs?

**Comment by mcd500** [comment]
I do not recall closing this issue, but it show that I have closed it. Was this issue closed automatically when I merged https://github.com/ietf-teep/teep-protocol/pull/112 ?

**Comment by dthaler** [comment]
> I do not recall closing this issue, but it show that I have closed it. Was this issue closed automatically when I merged #112 ?

Yes because the PR used the github keyword "Fixes".  Guess I will try to not do that in the PR description :)

**Comment by dthaler** [comment]
Fixed in draft -05

**Comment by mcd500** [comment]
Oh, I see, I will be careful and check any issues are closed with the merge from next time.
