### ISSUE TITLE
[hackathon] TA Signer or TC Signer

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#125]
Should we change the TA Signer to TC Signer?

We have changed the name of unit which is handled in TEEP message from Trusted Application to Trustiest Component.
In the current draft, the contents  of SUIT manifest which are TA Binaries and/or  Personalization Data are written as they are signed by TA Signer.

Maybe easier to understand to rename TA Signer to TC Signer.

**Comment by dthaler** [comment]
Agreed, this editorial fix needs to be done.   The arch draft always uses "Trusted Component Signer" now.

**Comment by mingpeiwk** [comment]
Agreed. Noticed some inconsistency in the definition of TC Signer that still cites TA, and will update altogether.

**Comment by dthaler** [comment]
Fixed in draft-06

**Comment by mcd500** [comment]
Thanks
