### ISSUE TITLE
[hackathon] token in teep message or using nonce in eat-claim-set

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#127]
Section Entity Attestation Token was added from draft-05.

The token in the current teep message or using nonce in eat-claim-set for matching the request and reply between TAM and TEEP device.

Which should we use in the future?
Both seem to work. 

Our current implementations use the token to keep track and binding the teep messages from the first QueryRequest to teep-success/teep-error.

**Comment by dthaler** [comment]
The intent is that the token is only used if attestation is not used.  So if the QueryRequest sets the attestation bit in data-items-requested, then there should be no token in the QueryRequest, just a challenge.

**Comment by kaduk** [comment]
This is mentioned in the slides at https://datatracker.ietf.org/meeting/110/materials/slides-110-teep-teep-protocol-00 .

My general sense is that if two fields have different semantics, even if they share the same format, it's preferred to use different codepoints to refer to them, to have a clear relationship between the codepoint (map key) and semantics.

If the semantics are similar and we are in a very constrained environment, exceptions to this can be reasonable, and I don't think I have enough data to take a hard stance one way or the other in this case.

**Comment by dthaler** [comment]
IETF 110 [minutes](https://datatracker.ietf.org/meeting/110/materials/minutes-110-teep-00) say:

> Issue #127: Use of token vs challenge in QueryRequest
> Since the token and challenge cannot both be present, should they be merged under a single
> CBOR label?
> Resolution already proposed by Ben K: preferably not, since they are semantically distinct.

**Comment by dthaler** [comment]
Fixed in draft-06

**Comment by mcd500** [comment]
Thanks
