### ISSUE TITLE
[hackathon] generating suit manifest for delete

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#128]
The unneeded-tc-list was delete in TEEP-TYPE-update from draft-05 since we decided to use the install, update and delete commands in suit manifest.

Honestly we just barely made deleting TC successfully working in this ietf110 hackathon with unneeded-tc-list and do not want to change it again, but would like to have support from the suit community for generating suit manifest for delete.

We looked into suit-manifest-generator and have been using generated manifest with install but could not find how to generate manifest with delete. We really appreciate help generating example manifest for deleting Trusted Components purposes.

**Comment by dthaler** [comment]
@bremoran has suit-manifest-generated been updated?

**Comment by dthaler** [comment]
Personally I don't think any change to the spec is warranted, just an implementation issue

**Comment by dthaler** [comment]
https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol#appendix-E.2 in draft-07 includes a sample manifest for delete.
