### ISSUE TITLE
I wonder if it is suitable for TEEP protocol to implement attestation using Remote Attestation of Intel SGX as below

### ISSUE THREAD

**Issue by itohdaisuke** [ietf-teep/teep-protocol#13]
There are three subjects;

1. Repeated QueryRequest - QueryResponse interactions in one attestation.
2. The EAT of QueryResponse has data for SGX Attestation.
3. The extensions of QueryRequest have data for SGX Attestation.

Each content is to be detailed in order. I hope you would read and may I have your opinion.

1. Repeated QueryRequest - QueryResponse interactions in one attestation.

For Remote Attestation of SGX to be put into practice, it is necessary to exchange messages between the TEEP Agent in a device and a TAM twice.
The following figure is from 'Intel_SGX_Developer_Reference_Linux_2.7.1_Open_Source'(https://download.01.org/intel-sgx/sgx-linux/2.7.1/docs/Intel_SGX_Developer_Reference_Linux_2.7.1_Open_Source.pdf, p.102).
![76475150-5c280580-6441-11ea-8050-6c18e97bbb59](https://user-images.githubusercontent.com/62082278/76715214-b80acb00-676e-11ea-8ef8-8831ac652b13.jpg)
(We can send msg0 with msg1 at step 10)

The connection is presented as ra_network_send_receive.
Corresponding to that, in terms of TEEP protocol it seems that exchanging QueryRequest and QueryResponse is to be done twice, doesn't it.

```
TAM                                         TEEP Agent
 Step1.QueryRequest ---------------------------->
 Step2.<----------------------------------------- QueryResponse(with EAT(msg0+msg1))
 Step3.QueryRequest(with Extention(msg2)) ------>
 Step4.<----------------------------------------- QueryResponse(with EAT(msg3))
GOOD or NG
```
(fig.1)

As summarized in fig.1, is it appropriate to implement the attestation of TEEP via repeated exchanges of QueryRequest and QueryResponse.

2. The EAT of QueryResponse has data for SGX Attestation.

At Step2 and Step4 in fig.1, the TEEP Agent ought to send to the TAM msg0, msg1, and msg3. Those are generated by the TEEP Agent and necessary for SGX Remote Attestation.

Is it correct to define custom claim identifier and send data packed in EAT of QueryResponse.

3. The extensions of QueryRequest has data for SGX Attestation.

At Step3 in fig.1, the TAM ought to send to the TEEP Agent msg2, which is generated by the TAM and necessary for SGX Remote Attestation.
Is it correct to define custom keys for the $$extensions part of QueryRequest and send data.

That is all.
With kind regards.

**Comment by dthaler** [comment]
My belief is: yes it is suitable.

If the QueryResponse contains attestation evidence that is just intermediate results, and the Verifier needs more information via a second exchange, then the TAM can generate another QueryRequest to initiate the second exchange.

**Comment by hannestschofenig** [comment]
With https://github.com/ietf-teep/teep-protocol/commit/97d3912a3f0edf153cdb8d026d0031737cbac0b1 can we consider this issue closed? Do we need to add text (similiar to what is described above) in the draft to explain the suitability of TEEP for SGX to others?

**Comment by dthaler** [comment]
My opinion: for any vendor-proprietary attestation mechanism, I think it's up to that mechanism or vendor to talk about how it can be used with the TEEP protocol, rather than the TEEP protocol talking about vendor specific mechanisms.   So my opinion is this can be closed.   We can confirm with the WG at the TEEP meeting if not confirmed before then.

**Comment by itohdaisuke** [comment]
Thank you. The reply you gave me settled my question.

**Comment by dthaler** [comment]
Addressed in draft-04
