### ISSUE TITLE
Is challenge mandatory or optional when attestation bit set

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#131]
The QueryResponse message has an optional “challenge” field used in creating Evidence, with the description:

> When a challenge is provided in the QueryRequest and an EAT is returned with the QueryResponse message then the challenge contained in this request MUST be copied into the nonce claim found in the EAT.

Q1: RATS attestation architecture doc explains attestation can use nonces, timestamps, or handles.  Does TEEP require nonce approach or is any of the approaches ok?

The original intent of the TEEP text was: any is ok, attestation bit can be set with challenge absent

Q2: But then how do Verifier & Agent agree on freshness approach?

The Evidence in the QueryResponse is sufficient to convey what the Agent used.  For example, EAT has separate claims for nonce vs timestamp (and presumably in the future, handle).   But how does the Verifier convey what it expects?

Some potential options include:

Option 1: force use of a single approach (narrows TEEP applicability)
Option 2: force Agent to support all (hard for constrained Agents)
Option 3: add field in QueryRequest like we did for supported ciphersuites (but TAM is just a passthrough, like for challenge, so like challenge the actual content would be obtained from the Verifier)
Option 4: overload challenge field and make the challenge field mandatory when attestation bit set

My preference would be option 3.

This issue is partially related to issue #127

**Comment by mcd500** [comment]
I also prefer option 3 and differently not for 2.

**Comment by dthaler** [comment]
Fixed in draft-06
