### ISSUE TITLE
[hackathon] handling of suit-commands bit in data-item-requested

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#145]
Section 4.2 defines a suit-commands bit in the data-item-requested in QueryRequest:

>       suit-commands (8)  With this value the TAM queries the TEEP Agent
>          for supported commands offered by the SUIT manifest
>          implementation.

However, there's no defined way in the QueryResponse to report this information.

Should the suit-commands bit simply be removed, and leave this to an extension?

**Comment by mcd500** [comment]
Resolved with PR https://github.com/ietf-teep/teep-protocol/pull/155
