### ISSUE TITLE
[hackathon] What is the "TEEP CBOR tag"?

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#147]
Section 4.1.1 says:

>    4.  Prepend the COSE object with the TEEP CBOR tag to indicate that
>        the CBOR-encoded message is indeed a TEEP message.

and section 4.1.2 says:

>    2.  Remove the TEEP message CBOR tag and verify that one of the COSE
>        CBOR tags follows it.

But nowhere does it explain what the "TEEP CBOR tag" is that is mentioned.

**Comment by mcd500** [comment]
CBOR tag is often seen in the cbor draft but I am also not sure what and how to use it here in TEEP. We may need help from CBOR team.
In the draft
https://datatracker.ietf.org/doc/html/rfc7049#section-2.4
https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml

**Comment by dthaler** [comment]
Presumably it refers to what is in https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol#section-10.4 but I am not sure how it is used in CBOR itself as it is not in any example or CDDL in the draft
