### ISSUE TITLE
CBOR type for TOKEN

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#15]
This is feedback from the virtual hackathon last week.
The CBOR type of TOKEN in the current draft is bstr (byte strings).
The TOKEN is used to match requests to responses.
For most of computer language, comparing the `string` is more inconvenient than the `int`.
The string matching in c language have to use strcmp() function instead of regular `if (token==1)`. 
Might good considering to changing to `int`? 
If the TOKEN do not expecting to have negative number, then CBORE unit type might be better/

I made a pull request for changing to `int`.
https://github.com/ietf-teep/teep-protocol/pull/14

Please let me know if you prefer `uint`. I will make the pull request.

**Comment by larsr** [comment]
I don't see why this is an improvement. The token could conceivably be an arbitrary hash or random byte string, not just an int.

**Comment by mcd500** [comment]
The discussion for the type of TOKEN have moved to the PR request bellow. Closing it.
https://github.com/ietf-teep/teep-protocol/pull/27
