### ISSUE TITLE
Delete wish from Client App to TAM

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#16]
This is from the https://github.com/ietf-teep/otrp-over-http/issues/8.

Would like to add member of informing insert or delete wish in the QueryResponse which is sent from Device to TAM.

For the situation that  Client App is installed at the Device would like to have the TA associated it from the authorized TAM.

QueryResponse = {
 // adding optional member
      ? request : uint
}

while the 
requests = [ + ( 
    install /
    delete /
)]

and use the TA_LIST for specifying the TA which Client App would like to install or delete.

**Comment by dthaler** [comment]
Install requests is a duplicate of issue #2 
This issue can track requests to delete a TA.
(This is not needed on some TEEs for which a TA can simply be deleted without the TAM's permission.)

**Comment by dthaler** [comment]
Last bullet of section 7.1 of the TEEP arch draft indicates this information is intended to be inside the attestation information (e.g., the "eat" field of the map) rather than separately in the QueryResponse.

**Comment by mcd500** [comment]
Solved by https://github.com/ietf-teep/teep-protocol/pull/47/files
Thanks

**Comment by dthaler** [comment]
Wait until draft is posted to close

**Comment by dthaler** [comment]
Fixed in draft-04

**Comment by mcd500** [comment]
Closing it since it is in draft 04
