### ISSUE TITLE
[hackathon] Simplify Ciphersuites

### ISSUE THREAD

**Issue by ko-isobe** [ietf-teep/teep-protocol#167]
In [draft-ietf-teep-protocol-07 Section 7](https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol-07#section-7), ciphersuites are defined.

The mentioned protection methods for TEEP messages in the current draft are signing and encryption.
Signature protection described in Section 4 is using COSE_Sign1 to authenticate messages. 
Encryption protection is to acquire confidentiality, described in Section 7, but the definition of using COSE_Encrypt is not defined yet.

Summarizing the previous discussion and consideration, the protection scheme of TEEP messages just utilizes COSE.
To simplify the ciphersuites, I would like to propose we only use [COSE Algorithms Registry](https://datatracker.ietf.org/doc/html/rfc8152#section-16.4) instead of creating TEEP original ciphersuites. It would make implementation of TEEP devices much easier since the SUIT manifest inside the TEEP message already uses COSE and the code for the COSE could be exactly reusable on both TEEP messages and the SUIT manifests.

If using the COSE registry, I propose the TEEP's ciphersuites are defined as the following style.

To specify signature algorithms:

;REQUIRED to implement: (alignment with the current proposed ciphersuites)
- teep-cose-algs /= cose-alg-es256
- teep-cose-algs /= cose-alg-eddsa

;OPTIONAL to implement:
- teep-cose-algs /= cose-alg-ps256
- teep-cose-algs /= cose-alg-ps384
- teep-cose-algs /= cose-alg-ps512
- teep-cose-algs /= cose-alg-rsaes-oaep-sha256
- teep-cose-algs /= cose-alg-rsaes-oaep-sha512

Even other protection methods(encryption, MAC?) are added in the future draft, ciphersuites also can be added from COSE registry from the link below.
https://www.iana.org/assignments/cose/cose.xhtml

**Comment by mcd500** [comment]
To make it easier for the teep device vendor how about let them chose only one?

```
;REQUIRED to implement either of one:

    teep-cose-algs /= cose-alg-es256
    teep-cose-algs /= cose-alg-eddsa
```

**Comment by mcd500** [comment]
This is the cddl description in suit.
```
   ;REQUIRED to implement:
   suit-cose-hash-algs /= cose-alg-sha-256

   ;OPTIONAL to implement:
   suit-cose-hash-algs /= cose-alg-shake128
   suit-cose-hash-algs /= cose-alg-sha-384
   suit-cose-hash-algs /= cose-alg-sha-512
   suit-cose-hash-algs /= cose-alg-shake256
```

How about to maximize aligning with suit and make it similar to bellow.
Adding recommendation will become similar to current teep draft.
```
;REQUIRED to implement:
    teep-cose-algs /= cose-alg-sha-256

;RECOMMENDED to implement:
    teep-cose-algs /= cose-alg-es256
    teep-cose-algs /= cose-alg-eddsa

;OPTIONAL to implement:
    teep-cose-algs /= cose-alg-shake128
    teep-cose-algs /= cose-alg-sha-384
    teep-cose-algs /= cose-alg-sha-512
    teep-cose-algs /= cose-alg-shake256
    teep-cose-algs /= cose-alg-ps256
    teep-cose-algs /= cose-alg-ps384
    teep-cose-algs /= cose-alg-ps512
    teep-cose-algs /= cose-alg-rsaes-oaep-sha256
    teep-cose-algs /= cose-alg-rsaes-oaep-sha512
```
