### ISSUE TITLE
[hackathon] Delete a Trusted Component SUIT Manifest seems to require update

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#168]
There is a "Delete a Trusted Component" SUIT Manifest in [Appendix E](https://github.com/ietf-teep/teep-protocol/blame/master/draft-ietf-teep-protocol.md#L1801).
I made the PR of suit delete manifest format based on my understanding bellow of reading the suit manifest draft.

- the suit manifest has suit-directive-unlink in the suit-install section
- the suit-manifest-sequence-number is larger than the manifest of the deleting Trusted Component

**Comment by kentakayama** [comment]
I wrote a PR but but I think we need more discussions.
Three ways came up to my mind, so please make any comments.
Detailed descriptions are in the #169 .

# Option 1: Create Unlink Manifest
```
/ SUIT_Envelope_Tagged / 107( {
  / manifest: / 3: << {
    / manifest-sequence-number / 2: 18446744073709551615 / large value /,
    / common / 3: << {
      / components / 2: [
        [h'00']
      ]
    },
    / install / 9: <<[
      / directive-set-component-index / 12, 0 / [h'00'] /,
      / directive-unlink / 33, 0
    ]>>
  } >>
} )
```

# Option 2-1: Implicitly Delete from Existing Manifest
```
/ SUIT_Envelope_Tagged / 107( {
  / manifest: / 3: << {
    / manifest-sequence-number / 2: 2,
    / common / 3: << {
      / components / 2: [
        [h'00']
      ]
    },
    / install / 9: <<[
      / directive-set-component-index / 12, 0 / [h'00'] /,
      / directive-override-parameters / 20, {
        / uri / 21: 'http://example.com/file.bin',
      },
      / directive-fetch / 21, 2 / change to `directive-unlink` when deleting /
    ]>>
  } >>
} )
```

# Option 2-2: Explicitly Delete from Existing Manifest
```
/ SUIT_Envelope_Tagged / 107( {
  / manifest: / 3: << {
    / manifest-sequence-number / 2: 2,
    / common / 3: << {
      / components / 2: [
        [h'00']
      ]
    },
    / install / 9: <<[
      / directive-set-component-index / 12, 0 / [h'00'] /,
      / directive-override-parameters / 20, {
        / uri / 21: 'http://example.com/file.bin',
      },
      / directive-fetch / 21, 2
    ]>>,
    / uninstall / <TBD> / explicitly describe how to delete this component / : <<[
      / directive-set-component-index / 12, 0 / [h'00'] /,
      / directive-unlink / 33, 0
    ]>>
  } >>
} )
```

**Comment by kentakayama** [comment]
According to the IETF112 TEEP discussion, the Option 1 Unlink Manifest above fits to SUIT philosophy: the device can unlink the Trusted Component(s) only when the SUIT Manifest Signer, or the Trusted Component Signer, creates the Unlink Manifest and delivers it.
This works well if the SUIT Manifest does not depend other Manifests, but I think it is still controversial due to the Multiple Trust Domains.

# New Issue?
I think it does not work well on some cases like below.
- SUIT Manifest A: contains Trusted Component A, was created by Signer A
- SUIT Manifest B: contains Trusted Component B, depends SUIT Manifest A, was created by Signer B

While installing SUIT Manifest B, SUIT Manifest A is fetched and Trusted Component A is installed by resolving the dependency. If the Signer B, however, wants to unlink the SUIT Manifest B and its depending SUIT Manifest A by creating Option 1 Unlink Manifest, the Signer B **CANNOT** unlink the SUIT Manifest A and its component because the Signer A has not created the Unlink Manifest of Trusted Component A. It may remain forever.

Though the current teep-protocol I-D defines `unneeded-tc-list` in the QueryResponse message, which can carry the identifier of Trusted Component A, the TAM still doesn't know how to unlink it because there is no Unlink Manifest for it.
Even though the Signer A creates the Unlink Manifest of A by answering the unlink request, the Signer A **DOES NOT** want to unlink it from all devices. It means, the timing when the Signer creates Unlink Maniefst and delivers it to the TAM is different from the timing the Signer wants unlink it.

# SUIT Manifest Extensions for Multiple Trust Domains I-D
The [original SUIT Manifest](https://datatracker.ietf.org/doc/html/draft-ietf-suit-manifest) covers only simple situation, the SUIT Manifests have single suit-manifest-sequence-number series and only 1 Signer exists.
Now for the complicated situation like TEEP, the dependency function and `suit-directive-unlink` command are defined in the [SUIT Manifest Extensions for Multiple Trust Domains](https://datatracker.ietf.org/doc/html/draft-moran-suit-trust-domains) I-D. I think we can contribute it.

And also, we need to re-think about the meaning of `suit-manifest-sequence-number`, because the Manifests A and B have the numbers separately. It is not only because the Signers are different, but also it could be considerable with 2 or more series of SUIT Manifests. It may be another meaning of [original definition in the SUIT Manifest](https://datatracker.ietf.org/doc/html/draft-ietf-suit-manifest#section-8.4.2) with such situation below:
- SUIT Manifest A: contains Trusted Component A, has suit-manifest-sequence-number = 2, was created by Signer A
- SUIT Manifest B: contains Trusted Component B, has suit-manifest-sequence-number = 1, was created by Signer A

Can we install both the Trusted Component A and B? Or do we need to combine them?
- SUIT Manifest A&B: contains Trusted Component A and B, has suit-manifest-sequence-number = 2, was created by Signer A

# Discussion
- what happens on TEEP Architecture, which has multiple trust domains such as the Signer, the TAM, the Device Owner, and the TEEP Agent?
- who can decide to unlink a component and when?
- when does the Signer have to create Unlink Manifest?
- is this could be a problem only with dependency?
- what does `suit-manifest-sequence-number` mean when there are multiple series of SUIT Manifests

**Comment by dthaler** [comment]
@mcd500 Now that PR #169 is merged, is this issue ready to close?

**Comment by dthaler** [comment]
Fixed in draft-08
