### ISSUE TITLE
TAM certificate caching

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#17]
As noted in https://github.com/ietf-teep/otrp-over-http/issues/12 the discussion of caching of the TAM's certificate by the TEEP Agent is missing from the protocol spec.

Specifically, as in OTrP, if the OCSP_DATA is cached, then the TEEP Agent should be able to directly send a QueryResponse without waiting for the initial QueryRequest.  This allows getting rid of an extra round trip, thus saving latency, bandwidth, and CPU cycles, all of which can be important for constrained nodes/networks.

**Comment by hannestschofenig** [comment]
I believe this issue is goes into the same direction as https://github.com/ietf-teep/teep-protocol/issues/40
