### ISSUE TITLE
[hackathon] For better ciphersuite type definition

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#183]
The `ciphersuite` type introduced by [#176 Pull Request](https://github.com/ietf-teep/teep-protocol/pull/176) seems just a replacement of previous `suite` type, and I think there might be better expression.

I think the most common TEEP use case currently assumed is COSE_Sign1 + (ES256 or EdDSA), i.e. public key based message authentication with only 1 signer.
It's much better that the updated `ciphersuite` can carry the COSE_Sign1 tag to distinguish with COSE_Sign.
Additionally, it would be better if it is adequate to represent [HPKE with COSE](https://datatracker.ietf.org/doc/draft-ietf-cose-hpke/) for upward compatibility, even encrypting whole TEEP messages are not so common case for now.

My draft proposal is:
```
teep-cose-sign-algs /= cose-alg-es256
teep-cose-sign-algs /= cose-alg-eddsa
teep-cose-sign-algs /= cose-alg-ps256
teep-cose-sign-algs /= cose-alg-ps384
teep-cose-sign-algs /= cose-alg-ps512
teep-cose-sign-algs /= cose-alg-rsa-oaep-256
teep-cose-sign-algs /= cose-alg-rsa-oaep-512
teep-cose-sign = [ COSE_Sign / COSE_Sign1, teep-cose-sign-algs ]

teep-cose-encrypt-algs /= cose-alg-accm-16-64-128
teep-cose-encrypt-algs /= cose-alg-gccm-16-64-128 / Currently Not Listed in TEEP Protocol /
teep-cose-encrypt-algs /= cose-alg-hpke-p256-hkdf256-gccm-16-64-128 / TBD in IANA /
teep-cose-encrypt = [ COSE_Encrypt / COSE_Encrypt0, teep-cose-encrypt-algs ]

teep-cose-mac-algs /= cose-alg-hmac-256
teep-cose-mac = [ COSE_Mac / COSE_Mac0, teep-cose-mac-algs ]

ciphersuite = [ * ( teep-cose-sign / teep-cose-encrypt / teep-cose-mac ) ]
```

For example, TEEP Protocol with COSE_Sign1 + ES256 would be represented by `[ [ COSE_Sign1, cose-alg-es256 ] ]`.
HPKE example would be like below.
```
[
  / layer0 / [ COSE_Encrypt, cose-alg-gccm-16-64-128 ],
  / layer1 / [ COSE_Encrypt, cose-alg-hpke-p256-hkdf256-gccm-16-64-128 ]
]
```

- Pros
  - The usage of the algorithm is explicitly specified by 6 COSE_* tags
  - The sequence of multiple algorithms can be expressed
    - e.g. sign then encrypt, encrypt then mac, etc.
  - This type definition may support also HPKE with COSE
    - i.e. encrypt then encrypt
  - This type definition potentially supports the hybrid mode of pre-quantum cryptography and post-quantum cryptography
- Cons
  - There is no consensus to use encrypt nor mac in TEEP Protocol security wrapper
  - Current TEEP Protocol uses public key based authentication and its messages are signed
    - Encrypting is quite heavy for some sort of devices
    - Encrypting TEEP Protocol messages themselves is discouraged in TEEP Architecture document

I think my draft proposal is not the best, and we need careful discussion and a lot of reviews.

**Comment by mcd500** [comment]
We have discussed the details of the cddl format with @kentakayama, @ko-isobe and others participating from Japan.
This includes the discussion at the IETF113 of having recommended and optional algorithms which could be used on TEEP.
We would like to make the PR with the following format.

```
;For ciphersuite from this line
COSE_Sign = 98
COSE_Sign1 = 18
COSE_Encrypt = 96
COSE_Encrypt0 = 16
COSE_Mac = 97
COSE_Mac0 = 17

;RECOMMENDED to implement:
teep-cose-algs /= cose-alg-hss-lms = -46

;OPTIONAL to implement any from IANA cose registry. Listing only partially:
teep-cose-algs /= cose-alg-es256 = -7
teep-cose-algs /= cose-alg-eddsa = -8
teep-cose-algs /= cose-alg-a256gcm = 3
teep-cose-algs /= cose-alg-hmac-256-256 = 5
teep-cose-algs /= cose-alg-hmac-384-385 = 6
teep-cose-algs /= cose-alg-hmac-512-512 = 7


teep-cose-sign = [ COSE_Sign / COSE_Sign1, teep-cose-algs ]
teep-cose-encrypt = [ COSE_Encrypt / COSE_Encrypt0, teep-cose-algs ]
teep-cose-mac = [ COSE_Mac / COSE_Mac0, teep-cose-algs ]

ciphersuite = [ * ( teep-cose-sign / teep-cose-encrypt / teep-cose-mac ) ]
```

**Comment by mcd500** [comment]
Made the PR https://github.com/ietf-teep/teep-protocol/pull/194

**Comment by mcd500** [comment]
@dthaler @hannestschofenig Please review

**Comment by dthaler** [comment]
Fixed in draft -09
