### ISSUE TITLE
[hackathon] Evidence-format is also required for EAT

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#184]
# Opinion
As EAT allows to be encoded with either CWT or JWT, we have to distinguish them.
`Evidence-format` is also required even the `evidence` is an EAT.

# Backgrounds
[Current draft](https://github.com/ietf-teep/teep-protocol/blob/0188f6b74661594bb329a54a5392963200d4eaf6/draft-ietf-teep-protocol.md?plain=1#L456-L459) says as below, but I think it MUST be present even if the evidence format is an EAT.

> evidence-format
>    The evidence-format parameter indicates the IANA Media Type of the
>    attestation evidence contained in the evidence parameter. It MUST
>    be present if the evidence parameter is present and the format is
>    not an EAT.

[IANA Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml) provides "application/jwt" and "application/cwt", which are appropriate as evidence-format value in my view.
How about to replace the block like this?

> evidence-format
>    The evidence-format parameter indicates the IANA Media Type of the
>    attestation evidence contained in the evidence parameter. **For example,**
>    **"application/jwt" MUST be present if the EAT format is JWT, and**
>    **"application/cwt" MUST be present if the EAT format is CWT.**

# Note
Another consideration is that the JWT is base64url encoded or not.
It MUST be not base64url encoded, I think.

**Comment by dthaler** [comment]
I think we should say the default value is "application/cwt"

**Comment by dthaler** [comment]
Fixed in draft -09
