### ISSUE TITLE
Clarify use of Attestation Results

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#185]
TAM requirements are for Attestation Results not evidence.
Should clarify that the Passport model is not illegal in TEEP even if it's not typical.
And clean up the EAT profile language about claims being Attestation Results, and maybe clarify the arch doc text as well if needed.

This issue is related to, but slightly different from #184

**Comment by mcd500** [comment]
@dthaler Do you mind working on wording to support both Back ground model and Passport model before the next IETF?

**Comment by dthaler** [comment]
Fixed in draft -09
