### ISSUE TITLE
remove IANA registry for data-item-requested

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#188]
draft-ietf-teep-protocol-08 says in section 4.2 under data-item-requested:

> Further values may be added in the future via IANA registration.

However the IANA considerations section defines no such registry.

**Comment by mcd500** [comment]
@dthaler I made the PR for removing IANA registration portion in data-item-requested at https://github.com/ietf-teep/teep-protocol/pull/205
If it OK, I will merge it. Thanks.
