### ISSUE TITLE
Reliably getting TEE properties

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#189]
Currently evidence in the QueryResponse is an optional field, and the QueryRequest can specify the attestation bit to request it.

If the evidence is NOT mandatory, then the QueryResponse today has no reliable way to learn parameters such as device identifying information and TEE identifying information, which seem critical to the task of being able to determine which Trusted Components to install in the TEE.

Options:
1) Make evidence mandatory in the QueryResponse and remove the attestation bit from data-items-requested
2) Make attestation mandatory but allow it to be either passed inside the TEEP protocol or in a transport protocol (e.g., HTTPS terminating inside the TEE as in model C of figure 5 in the architecture draft).  The attestation bit shouldn't be needed in data-items-requested here either since an implementation could know whether the transport included it inside the TEE or not
3) Make use of SUIT Reports in the QueryResponse mandatory and put the system information there.   This means that a TAM would be able to access them without relying on a Verifier to put relevant claims in Attestation Results so could ease interop with more Verifiers.
4) Some hybrid that allows more than one of the above in implementations but only uses one in any particular message exchange.

**Comment by ko-isobe** [comment]
IMHO, for just conveying system information, full SUIT Report format is too bigger in this requirement.
Additionally, in TEEP protocol SUIT Reports will have two semantics; reporting system info in QueryResponse and reporting results in Error message. That may lead to confuse in handling SUIT reports.
Is adding `suit-system-properties` value in QueryReponse simply as following style insufficient for the requirement?

``
 ? system-information => [ + suit-system-properties ]
``

Thanks,

**Comment by mcd500** [comment]
Hi Dave,
I completely agree of necessity of including device identifying information and TEE identifying information in the QueryResponse.

This is the cddl for the SUIT-Report:
```
SUIT_Report = {
  suit-report-manifest-digest => SUIT_Digest,
  ? suit-report-manifest-uri  => tstr,
  ? suit-report-nonce         => bstr,
  suit-report-records         => [ * SUIT_Record ],
  ? suit-system-properties      => [ + system-property-claims ],
  suit-report-result          => true / {
    suit-report-result-code   => int, ; could condense to enum later
    suit-report-result-record => SUIT_Record,
  }
}
system-property-claims = {
  system-component-id => SUIT_Component_Identifier,
  + SUIT_Parameters,
}
```

This is the cddl for the SUIT-Parameters:
```
SUIT_Parameters //= SUIT_Parameter_Strict_Order
SUIT_Parameters //= SUIT_Parameter_Coerce_Condition_Failure
SUIT_Parameters //= SUIT_Parameter_Vendor_ID
SUIT_Parameters //= SUIT_Parameter_Class_ID
SUIT_Parameters //= SUIT_Parameter_Device_ID
SUIT_Parameters //= SUIT_Parameter_URI_List
SUIT_Parameters //= SUIT_Parameter_Encryption_Info
SUIT_Parameters //= SUIT_Parameter_Compression_Info
SUIT_Parameters //= SUIT_Parameter_Unpack_Info
SUIT_Parameters //= SUIT_Parameter_Source_Component
SUIT_Parameters //= SUIT_Parameter_Image_Digest
SUIT_Parameters //= SUIT_Parameter_Image_Size
SUIT_Parameters //= SUIT_Parameter_Custom

SUIT_Parameter_Strict_Order = (1 => bool)
SUIT_Parameter_Coerce_Condition_Failure = (2 => bool)
SUIT_Parameter_Vendor_ID = (3 => bstr)
SUIT_Parameter_Class_ID = (4 => bstr)
SUIT_Parameter_Device_ID = (5 => bstr)
SUIT_Parameter_URI_List = (6 => bstr .cbor SUIT_URI_List)
SUIT_Parameter_Encryption_Info = (7 => bstr .cbor SUIT_Encryption_Info)
SUIT_Parameter_Compression_Info = (8 => bstr .cbor SUIT_Compression_Info)
SUIT_Parameter_Unpack_Info = (9 => bstr .cbor SUIT_Unpack_Info)
SUIT_Parameter_Source_Component = (10 => bstr .cbor SUIT_Component_Identifier)
SUIT_Parameter_Image_Digest = (11 => bstr .cbor SUIT_Digest)
SUIT_Parameter_Image_Size = (12 => uint)
SUIT_Parameter_Custom = (nint => int/bool/bstr)
```

The SUIT_Parameters might be better fit for carrying the device identifying information and TEE identifying information than the SUIT-Report.

**Comment by dthaler** [comment]
Fixed in draft -09

**Comment by dthaler** [comment]
Hackathon 114 discussion:
there are 4 possible ways to get TEE properties in a QueryResponse

1) In Attestation Results.  However this depends on the Verifier actually copying the information into the Attestation Results, which may be too burdensome in some cases.
2) In SUIT Reports.  However, this depends on the Device actually generating SUIT Reports at boot time, and making sure they include this info.  This is what draft -09 did, but some believe this is too burdensome for some TEEs which may not use SUIT for boot.
3) In the TC List.  However, this is really for components that can be updated via TEEP, not for hardware properties.
4) In some new field.  Akira and Hannes both preferred this option.

**Comment by mcd500** [comment]
Created PR https://github.com/ietf-teep/teep-protocol/pull/228  for the fourth option.

**Comment by dthaler** [comment]
Fixed in draft -10
