### ISSUE TITLE
Too big challenge size

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#202]
This is about the challenge in the current query-request.

I think the maximum size 512 of challenge is too big and would like to revert to `.size (8..64)`

In the current TEEP Protocol I-D, [the challenge field](https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol-08#section-4.2) can be used for EAT evidence,
and [EAT Nonce Claim](https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat-12#section-3.3) is 8 to 64 byte.

We have expanded the size to 512 bytes from the hackathon activity in the past with issue https://github.com/ietf-teep/teep-protocol/issues/130.

If we carry the Intel SGX Remote Attestation QUOTE in QueryResponse evidence, probably the most adequate challenge value would be `sgx_quote_nonce_t` which is used in sgx_get_quote function and has the size of 16 bytes.

The `sgx_target_info_t` contains the hash value of the enclave in the device, which is difficult to have in the QueryRequest sent from TAM.

The challenge in the QueryRequest is used for ensuring the freshness of the attestation evidence, so using `sgx_quote_nonce_t` is more reasonable.

I have researched for the challenge usage with Intel SGX:
- http://www.sgx101.com/portfolio/remote_attestation/
- Intel® Software Guard Extensions (Intel® SGX) SDK for Windows* OS
- https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf#page=15

**Comment by mcd500** [comment]
These are the definitions.
https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_quote.h
```
typedef struct _quote_nonce
{
    uint8_t             rand[16];
} sgx_quote_nonce_t;
```

https://github.com/openenclave/openenclave/blob/master/include/openenclave/bits/sgx/sgxtypes.h
```
typedef struct _sgx_target_info
{
    /* (0) MRENCLAVE (hash of target enclave) */
    uint8_t mrenclave[OE_SHA256_SIZE];

    /* (32) ATTRIBUTES of target enclave */
    sgx_attributes_t attributes;

    /* (48) Reserved */
    uint8_t reserved1[4];

    /* (52) MISCSELECT field of target enclave */
    uint32_t misc_select;

    /* (56) Reserved */
    uint8_t reserved2[456];
} sgx_target_info_t;
```

The sgx_target_info_t is total 512 bytes containing hash value of enclave. The QueryRequest is the first teep message sent from the TAM to the Device, and having enclave hash value from the TAM is probably unlikely to be required.

**Comment by mcd500** [comment]
@dthaler I believe it is OK to merge the PR.https://github.com/ietf-teep/teep-protocol/pull/203

**Comment by mcd500** [comment]
Oh, I did not realize the hash value is the challenge was going to be used for containing the hash value of the TAM.
I will discuss with @kentakayama and others.

**Comment by dthaler** [comment]
@mcd500 Any conclusion?  Can we close this issue?

**Comment by dthaler** [comment]
Discussed at hackathon, ok to close
