### ISSUE TITLE
Hackathon 116: Synchronize draft in markdown file and cddl file

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#208]
While updating the draft written in the markdown file and fixing cddl file in separated pull requests, the contents of the description of teep messages in cddl format are staring to diverse between the cddl definition of the teep message in main body of markdown file and the full cddl in the example section.

I will make the scripts to synchronize them.

**Comment by dthaler** [comment]
@mcd500 is this one done now?

**Comment by mcd500** [comment]
We will fix this during the IETF 116 hackathon this weekend.

**Comment by dthaler** [comment]
@mcd500 is this finally fixed by PR #328?

**Comment by mcd500** [comment]
@dthaler Yes, this issue is finished with the two PRs, https://github.com/ietf-teep/teep-protocol/pull/322, https://github.com/ietf-teep/teep-protocol/pull/328.

**Comment by dthaler** [comment]
Fixed in draft -13

**Comment by mcd500** [comment]
Closing old issue.
