### ISSUE TITLE
TEEP message format in CDDL

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/teep-protocol#21]
Akira suggested the following message format:

```

    TEEP_msg-authenc-wrapper = 1
    TEEP_message = 2

    TEEP_Msg_AuthEnc_Wrapper = [ *(COSE_Mac_Tagged /
                                   COSE_Sign_Tagged /
                                   COSE_Mac0_Tagged /
                                   COSE_Sign1_Tagged)]

    TEEP_Outer_Wrapper = {
        TEEP_msg-authenc-wrapper    => bstr .cbor
                                       TEEP_Msg_AuthEnc_Wrapper / nil,
        TEEP-message                => bstr .cbor
                                       (TEEP_QueryRequest /
                                        TEEP_QueryResponse /
                                        TEEP_TrustedAppInstall /
                                        TEEP_TrustedAppDelete /
                                        TEEP_Error /
                                        TEEP_Success ),
    }

TEEP_TYPE_QueryRequest      = 1
TEEP_TYPE_QueryResponse     = 2
TEEP_TYPE_TrustedAppInstall = 3
TEEP_TYPE_TrustedAppDelete  = 4
TEEP_TYPE_TEEP_Error        = 5
TEEP_TYPE_TEEP_Success      = 6

TEEP_attestation   = 1
TEEP_trusted_apps  = 2
TEEP_extensions    = 3
TEEP_suit_commands = 4

TEEP_REQUEST_COMMAND /= TEEP_attestation TEEP_REQUEST_COMMAND /= TEEP_trusted_apps TEEP_REQUEST_COMMAND /= TEEP_extensions TEEP_REQUEST_COMMAND /= TEEP_suit_commands

TEEP_AES-CCM-16-64-128_HMAC256/256_X25519_EdDSA = 1
TEEP_AES-CCM-16-64-128_HMAC256/256_P-256_ES256  = 2

TEEP_suite /= TEEP_AES-CCM-16-64-128_HMAC256/256_X25519_EdDSA
TEEP_suite /= TEEP_AES-CCM-16-64-128_HMAC256/256_P-256_ES256

TEEP_version = uint .size 4

TEEP_TYPE         = 1
TEEP_TOKEN        = 2
TEEP_REQUEST      = 3
TEEP_CIPHER_SUITE = 4
TEEP_NONCE        = 5
TEEP_VERSION      = 6
TEEP_OCSP_DATA    = 7

    TEEP_QueryRequest = {
         TEEP_TYPE => uint .size 1 TEEP_TYPE_QueryRequest,
         TEEP_TOKEN => uint .size 4,
         TEEP_REQUEST => uint .size 1 TEEP_REQUEST_COMMAND,
         ? TEEP_CIPHER_SUITE => uint .size 1 [+TEEP_suite],
         ? TEEP_NONCE => bstr .size (8..64),
         ? TEEP_VERSION => [+TEEP_version],
         ? TEEP_OCSP_DATA => bstr,
         * $$extensions
    }

TEEP_install = 1
TEEP_delete  = 2
TEEP_update  = 3

TEEP_DEVICE_DESIRE /= TEEP_install
TEEP_DEVICE_DESIRE /= TEEP_delete
TEEP_DEVICE_DESIRE /= TEEP_update

TEEP_SELECTED_CIPHER_SUITE = 8
TEEP_SELECTED_VERSION      = 9
TEEP_EAT                   = 10
TEEP_TA_LIST               = 11
TEEP_EXT_LIST              = 12

    TEEP_QueryResponse = {
         TEEP_TYPE =>  uint .size 1 TEEP_TYPE_QueryResponse,
         TEEP_TOKEN => uint .size 4,
         ? TEEP_DEVICE_REQUEST => uint .size 1 TEEP_DEVICE_DESIRE,
         ? TEEP_SELECTED_CIPHER_SUITE => uint .size 1 TEEP_suite,
         ? TEEP_SELECTED_VERSION => TEEP_version,
         ? TEEP_EAT => bstr,
         ? TEEP_TA_LIST  => [+bstr],
         ? TEEP_EXT_LIST => [+ext_info],
         * $$extensions
    }

```

**Comment by cabo** [comment]
One discussion we had in the virtual interim was whether the mandatory parts should be in an array.

**Comment by cabo** [comment]
The syntax `uint .size 1 TEEP_TYPE_QueryResponse` is not quite CDDL.
TEEP_TYPE_QueryResponse actually already is .size 1, so that information is redundant.
So you can just write `TEEP_TYPE_QueryResponse` here.

**Comment by cabo** [comment]
I might have time next week to make an edit round at this proposal.

**Comment by mcd500** [comment]
@cabo as the discussion at the interim meeting yesterday, to change the map to array, is it going to be [ ] from { }?

**Comment by dthaler** [comment]
My initial Berlin hackathon implementation used an array for the initial QueryResponse, here's an example in CBOR diagnostic format:
[1, h'1C76CB4EF2665BC68B9198E76EE21C71', [2]]

That's still missing the optional fields, so I'd put a map at the end of the array for those, but since there were no labels defined, I didn't do that yet.

This means the required fields (TYPE, TOKEN, REQUEST) are always at the beginning in a guaranteed offset (well, REQUEST _will_ be at a fixed offset once TOKEN is changed to a uint...), easing parsing.

**Comment by hannestschofenig** [comment]
I want to make sure that I understand the tentative conclusion from our virtual interim meeting yesterday correctly. The suggestion is to use an array for the mandatory fields of the requests and to use a map for the rest. 

Is this what you had in mind? In the QueryRequest the first 3 elements of the array are type, token, requested followed by the last array entry, which is a map containing the optional parameters found in the QueryRequest message? 

Here is an example: 
[1, h'1C76CB4EF2665BC68B9198E76EE21C71', [2], {3:1, 5: 1}]

Is my understanding correct?

**Comment by mcd500** [comment]
I think the example
```
[1, h'1C76CB4EF2665BC68B9198E76EE21C71', [2], ...]
```
is based on when it was 
```
QueryRequest = {
     TYPE : int,  // TYPE is 1 for QueryRequest
     TOKEN : bstr, // TOKEN using 1C76CB4EF2665BC68B9198E76EE21C71
     REQUEST : [+data_item], // using 2 here as an example
...
```

However, it is much larger binary.

Converting the above cddl in binary on the fly only with my memory without referring cbor or cddl draft right now, it is something like
```

```
A4 // the map is A? and number of members, so if it has four members then it will be A4
h'45950554' // TYPE label name in bstr will be embedded in map
01 // 1 for TYPE value
h'45F4B454E4' // TOKEN label name in bstr will be embedded in map
h'1C76CB4EF2665BC68B9198E76EE21C71' // value for TOKEN in bstr
81 //  the array is 8? and number of members, so if it has one member then it will be 81
02
and goes on...
```
Using tag will convert label name in bstr to int but still the int will be embedded in map
```
A4 // the map is A? and number of members, so if it has four members then it will be A4
01 // TYPE label name in uint in map
01 // 1 for TYPE value
02 // TOKEN label name in uint in map
h'1C76CB4EF2665BC68B9198E76EE21C71' // value for TOKEN in bstr
81 //  the array is 8? and number of members, so if it has one member then it will be 81
02
and goes on...
```
This is the main reason I was trying to use uint as much as possible than bstr in teep.
(I have not reconfirmed my hand binary converting... so it might have mistakes...)

**Comment by cabo** [comment]
Hi Akira,

I was trying to write up a proposal, but got stuck when the XML didn’t build.

I’ll generate a proposal that encodes into something in the next couple of days.

Grüße, Carsten

**Comment by mcd500** [comment]
This is trying to replicate the discussion at the interim meeting last night for moving on to use array and uint in teep as Hannes and Dave mentioning above.
I am not sure this is the right cddl format in array but let me try.

I need help from Carsten here. :)

```
TEEP_TYPE = uint .size 1 TEEP_TYPE_QueryRequest
TEEP_TOKEN = uint .size 8 // 1C76CB4E
TEEP_REQUEST /= uint .size 1 TEEP_attestation
TEEP_REQUEST /= uint .size 1 TEEP_trusted_apps
TEEP_REQUEST /= uint .size 1 TEEP_extensions
TEEP_REQUEST /= uint .size 1 TEEP_suit_commands

TEEP_QueryRequest = [
        TEEP_TYPE,   // 1 for TYPE value of QueryRequest
        TEEP_TOKEN, 
        +TEEP_REQUEST, // 2 is TEEP_trusted_apps
   ...
]
```

```
84 // the array is 8? and number of members, so if it has four members then it will be A4
01 // 1 for TYPE value
1B 1C 76 CB 4E // TOKEN  being '1C76CB4E' in 4bytes uint
02 // 2 is TEEP_trusted_apps
...
```

Looks really nice in binary.

I think I need to sleep since it was late last night but one last comment.

**Comment by mcd500** [comment]
The revising the cddl format is discussed at the PR here.
https://github.com/ietf-teep/teep-protocol/pull/27

**Comment by hannestschofenig** [comment]
I merged the proposed CDDL into the draft and therefore close this issue. 
(14th April 2020)
