### ISSUE TITLE
SUIT-Report's full CDDL data definition for TEEP Protocol

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#212]
To verify the syntax of the cddl for the current TEEP Protocol, it requires two additional cddl data definitions from suit-manifest and suit-report.

The cddl file for the suit-manifest is able to obtain from the following github link.
https://raw.githubusercontent.com/suit-wg/manifest-spec/master/draft-ietf-suit-manifest.cddl

For the cddl file for the suit-report, we have to create it manually from the following draft.
https://www.ietf.org/archive/id/draft-ietf-suit-report-01.html

I would like to propose using the following cddl file in the mean time for the suit-report which I created manually.
```
SUIT_Report = {
  suit-report-manifest-digest => SUIT_Digest,
  ? suit-report-manifest-uri  => tstr,
  ? suit-report-nonce         => bstr,
  suit-report-records         => [ * SUIT_Record ],
  ? suit-system-properties      => [ + system-property-claims ],
  suit-report-result          => true / {
    suit-report-result-code   => int, ; could condense to enum later
    suit-report-result-record => SUIT_Record,
  }
}
system-property-claims = {
  system-component-id => SUIT_Component_Identifier,
  + SUIT_Parameters,
}

suit-record-manifest-id = 1
suit-record-manifest-section = 2
suit-record-section-offset = 3
suit-record-component-index = 4
suit-record-dependency-index = 5
suit-record-properties = 6

suit-report-manifest-digest = 7
suit-report-manifest-uri = 8
suit-report-nonce = 9
suit-report-records = 10
suit-system-properties = 11
suit-report-result = 12
suit-report-result-code = 13
suit-report-result-record = 14
system-component-id = 15
```

**Comment by mcd500** [comment]
I am thinking to put this as the file name 'suit-report.cddl' in this teep-protocol repository until the suit-report.cddl will be obtainable from other places.

**Comment by mcd500** [comment]
This is for https://github.com/ietf-teep/teep-protocol/issues/198 and https://github.com/ietf-teep/teep-protocol/issues/208

**Comment by dthaler** [comment]
@mcd500 My understanding is that this issue does not affect the actual Internet Draft itself, only the ability to verify correctness of the CDDL in it.  Is that correct?  If so, this does not affect the I-D deadline.

**Comment by mcd500** [comment]
@dthaler Yes, this issue does not affect the actual Internet Draft itself, only the ability to verify correctness of the CDDL in the draft.
It does not affect the I-D deadline for this draft.

**Comment by mcd500** [comment]
This issue is fixed at
https://github.com/ietf-teep/teep-protocol/blob/master/cddl/Makefile#L47-L48
during the IETF 115 hackathon.
Will close it.
