### ISSUE TITLE
full EAT CDDL example in TEEP Protocol

### ISSUE THREAD

**Issue by ko-isobe** [ietf-teep/teep-protocol#213]
@mcd500 and I wrote a full EAT CDDL example for the EAT profile.
It's useful for readers to understand and make an integration of TEEP and RATS.
We added the following items from the current EAT profile.

1. Define `teep-evidence` and `teep-attestation-result` to indicate an EAT could have Evidence and Attestation Result separately.
In EAT, Evidence and Attestation Results can be expressed by the same format.
To distinguish between evidence and Attestation Result, define `teep-attestation-result` and it has an attestation result field as `result`.

2. Add `hash-entries` in teep-evidence
As discussed at #189, Verifiers in the back of TAM or TAM would require the system information and the hash values of TEE-OS or equivalent software to verify it.
We add the `hash-entries` in TEEP's EAT sample to convey such software's information in evidence.  

```
attestation-payload = [
  type: $TEEP-payload-type,
  attestation-body: teep-evidence / teep-attestation-result / tstr / bstr
]

$TEEP-payload-type /= TEEP-evidence
$TEEP-payload-type /= TEEP-attestation-result
TEEP-evidence = 1
TEEP-attestation-result = 2

teep-attestation-result = [
  result: bool,
  target: teep-evidence
]

teep-evidence = {
  ? ueid-label => ueid-type,
  ? oemid => oemid-pen / oemid-ieee / oemid-random,
  ? class-identifier => RFC4122_UUID,
  ? hardware-model-label => hardware-model-type,
  ? hardware-version-label => hardware-version-type,
  ? sw-name-label => tstr,
  ? sw-version-label => sw-version-type,
  ? nonce-label => nonce-type / [ 2 * nonce-type ],
  ? hash-entries => [ + hash-entry ] ; hash value of TEE or device
}

ueid-type =>  bstr .size (7..33)

oemid-pen = int

oemid-ieee = oemid-ieee-cbor
oemid-ieee-cbor = bstr .size 3

oemid-random = oemid-random-cbor
oemid-random-cbor = bstr .size 16

RFC4122_UUID = #6.37(bstr)

base64-url-text = tstr .regexp "[A-Za-z0-9_=-]+"

hardware-model-type = base64-url-text bytes .size (1..32)

$version-scheme /= multipartnumeric
$version-scheme /= multipartnumeric-suffix
$version-scheme /= alphanumeric
$version-scheme /= decimal
$version-scheme /= semver
$version-scheme /= int / text

hardware-version-type = [
    version:  tstr,
    ? scheme:  $version-scheme
]

sw-version-type = [
    version:  tstr
    ? scheme:  $version-scheme
]

nonce-type = bstr .size (8..64)

hash-entry = [
   hash-alg-id: int,
   hash-value: bytes,
]

```

**Comment by dthaler** [comment]
@mcd500 I do not believe a change to the `attestation-payload` definition is needed.  Instead of the proposed `type`, we can just use different media types with attestation-payload-format.

**Comment by dthaler** [comment]
Discussed at hackathon and filed issue #221 to make manifests claim be usable (instead of sw-version-type).
I'd propose we can now close this issue as a result and just use that issue to track.
@mcd500 @ko-isobe would you agree?
