### ISSUE TITLE
May require one more message for attestation

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#215]
This issue is related to https://github.com/ietf-teep/teep-protocol/issues/214.
Currently we have defined QueryRequest and QueryResponse messages between the TAM and the device before TAM will send the update message.

When we were considering implementation on local attestation on SGX, it required one more message as follows.

* QueryRequest from TAM to Device: challenge containing sgx_target_info_t
* QueryResponse from Device to TAM: attestation-payload containing sgx_report_t
* additional message from TAM to Device: containing at least sgx_report_t 

We would like to start discussing whether we should make an optional message for the local attestation purpose or piggy back the last sgx_report_t on the Update message from TAM to Device.

**Comment by dthaler** [comment]
@mcd500 Can you elaborate on why "additional message from TAM to Device: containing at least sgx_report_t" is needed?  Is this for the TAM's own `sgx_report_t` or what?

**Comment by mcd500** [comment]
@dthaler Sure, this is the topic I would like to talk during at the hackathon of the IETF114.

**Comment by dthaler** [comment]
Discussed during Hackathon
If SGX local attestation needed where TAM and TEEP Agent are on same device, then either:
a) the final REPORT from the Verifier might not need to be sent back to the TEEP Agent and just be used by the TAM, OR
b) A future TEEP extension can define a way to pass the final REPORT in a message to the TEEP Agent from the TAM, e.g., via extension in the QueryRequest

So the proposed resolution is to not address in the main spec

**Comment by dthaler** [comment]
Hackathon update: this isn't just for local attestation

Slide 8 of https://datatracker.ietf.org/meeting/105/materials/slides-105-teep-sessb-teep-rats-alignment-01 shows Attestation Result in a message coming from TAM to TEEP Agent.  We don't have this facility anywhere in draft -09 at present.  Discussed adding it as an option to the Update message.

**Comment by dthaler** [comment]
Fixed in draft-10
