### ISSUE TITLE
Which freshness mechanism(s) are MTI

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#235]
Each freshness mechanism requires explicit implementation support in a TAM and a TEEP Agent.

https://www.ietf.org/archive/id/draft-ietf-teep-protocol-09.html#freshness-mechanisms lists three such mechanisms.  
* Nonce is specified in [EAT section 4.1](https://www.ietf.org/archive/id/draft-ietf-rats-eat-14.html#name-nonce-claim-nonce), though that fact isn't mentioned in the TEEP freshness section, only the EAT profile section
* Timestamp is specified in [EAT section 4.3.2](https://www.ietf.org/archive/id/draft-ietf-rats-eat-14.html#name-timestamp-claim-iat), but requiring timestamp would also require a time synchronization protocol and a trusted source of local relative time, which may not be available in a TEE
* Epoch ID details are not specified at present

I propose:
* MUST support Nonce
* MAY support Timestamp if an implementation has a trusted source of local relative time and implements some secure time synchronization protocol within the TEE
* MAY support any other freshness mechanisms that appear in the IANA registry (which per PR #223 addressing issue #226, is moved to a separate spec)
* Remove mention of Epoch ID from this spec (left to an extension)

**Comment by dthaler** [comment]
@mcd500 @hannestschofenig @mingpeiwk @kentakayama @ko-isobe here's another issue to review

**Comment by dthaler** [comment]
If an implementation uses a proprietary attestation format, it might be using a proprietary freshness mechanism rather than being equivalent to one of the defined ones.  If so, it probably needs to register a new freshness mechanism value to be usable with TEEP.

Also, [section 4.2](https://www.ietf.org/archive/id/draft-ietf-teep-protocol-09.html#name-queryrequest-message) doesn't currently say it, but I think supported-freshness-mechanisms only needs to be present in the QueryRequest if the attestation bit is set in data-item-requested.

**Comment by kentakayama** [comment]
I agree with you, but I think also "There is no MTI freshness mechanism but implementing Nonce is RECOMMENDED" is fine, because attestation is currently optional.

**Comment by dthaler** [comment]
Fixed in draft-11
