### ISSUE TITLE
how does omitting eat profile work with bis documents?

### ISSUE THREAD

**Issue by mcr** [ietf-teep/teep-protocol#240]
section 4.3:
} The absence of this parameter indicates that the format is "application/eat-cwt;
} profile=https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol-10
} (RFC-editor: upon RFC publication, replace URI above with
} "https://www.rfc-editor.org/info/rfcXXXX" where XXXX is the RFC number of
} this document.) It MUST be present if the attestation-payload parameter is
} present and the format is not an EAT in CWT format with the profile defined
} below in Section 5.

If we revise this document rfcXXXX-bis, then what will the absense of the payload format mean?
It feels like premature optimization to set a default here.
I think that the profile should always be present, or never present.

**Comment by dthaler** [comment]
> If we revise this document rfcXXXX-bis, then what will the absense of the payload format mean?
> It feels like premature optimization to set a default here.
> I think that the profile should always be present, or never present.

@mcr if we revise the document to rfcXXXX-bis then presumably we would bump the version value used in the selected-version parameter and the default would be specified by that version.  So saying the default profile for version 0 (as specified in this RFC) is the profile as specified in this RFC seems consistent.   I see no issue here given the 'version' field is in parallel.  We just say that each version defines what the default profile is for that version.

**Comment by dthaler** [comment]
Fixed in draft-11
