### ISSUE TITLE
what are alternatives to EAT?

### ISSUE THREAD

**Issue by mcr** [ietf-teep/teep-protocol#241]
section 4.3.1:
} When an Entity Attestation Token is used

… and when EAT is not used?
There are quite a number of places where the document says "when EAT..." and
to me they read like stealth SHOULDs.   I understand that the document wants to
enable other attestation systems other than EAT, and I'm okay with that.
I'm not sure what to suggest, but it feels like a documentation bug.

such as:
 section 5:
 } While the TEEP protocol does not require use of EAT, use of EAT is
 } encouraged and Section 4.3

 mcr: Need to list alternatives and reasons not to use EAT.

Probably, this document needs to say SHOULD use EAT in some section, and then give the outs.

**Comment by dthaler** [comment]
EAT is not yet a standard or deployed, whereas various vendor-specific formats (e.g., Intel's SGX Reports) are widely deployed.   Since the Evidence is opaque to the TAM, any other format can be used between an Attester and a Verifier and the TAM will simply relay it on without parsing it.  SHOULD would be too strong for EAT, since the format of Evidence is opaque to the TEEP protocol... neither the TEEP Agent nor the TAM care (those roles neither produce nor consume Evidence per se).

**Comment by mcr** [comment]
Is there an alternative section to "When EAT is used ..., otherwise when TEEP transports a legacy report, then XYZ."

**Comment by dthaler** [comment]
> Is there an alternative section to "When EAT is used ..., otherwise when TEEP transports a legacy report, then XYZ."

Section 7.1.1 is intended to do exactly that, where "the media type defined in section 5" is an EAT with the TEEP profile:

> If a QueryResponse message is received that contains an attestation-payload, the TAM checks whether it contains Evidence or an Attesation Result by inspecting the attestation-payload-format parameter. The media type defined in [Section 5](https://www.ietf.org/archive/id/draft-ietf-teep-protocol-10.html#eat) indicates an Attestation Result, though future extensions might also indicate other Attestation Result formats in the future. Any other unrecognized value indicates Evidence. If it contains an Attesation Result, processing continues as in [Section 7.1.1.1](https://www.ietf.org/archive/id/draft-ietf-teep-protocol-10.html#attestation-result).
> 
> If the QueryResponse is instead determined to contain Evidence, the TAM passes the Evidence (via some mechanism out of scope of this document) to an attestation Verifier (see [[I-D.ietf-rats-architecture](https://www.ietf.org/archive/id/draft-ietf-teep-protocol-10.html#I-D.ietf-rats-architecture)]) to determine whether the Agent is in a trustworthy state. Once the TAM receives an Attestation Result from the Verifier, processing continues as in [Section 7.1.1.1](https://www.ietf.org/archive/id/draft-ietf-teep-protocol-10.html#attestation-result).

**Comment by dthaler** [comment]
Fixed in draft-11
