### ISSUE TITLE
examples in section 4 are really use scenarios for update

### ISSUE THREAD

**Issue by mcr** [ietf-teep/teep-protocol#242]
section 4.4.1:
} Example 1: Having one SUIT Manifest pointing to a URI of a Trusted Component Binary

I don't like them being called examples. They aren't things I can ignore.
I think that they are usage scenarios, and there seem to be four important ones.

**Comment by mcd500** [comment]
The changes #255 is merged.

**Comment by dthaler** [comment]
Fixed in draft-11
