### ISSUE TITLE
duration of TAM/TEEP Agent may be very long

### ISSUE THREAD

**Issue by mcr** [ietf-teep/teep-protocol#244]
section 7.1.2:
} Hence, depending on the freshness mechanism in use, the TAM may need to
} store data (e.g., a nonce) for some time.

This also suggests that for mobile devices that it may be hours to days before before right things are installed if they require unmetered WIFI to get the right pieces. The mobile device might change IP addresses and even geographies during that period, and it might be that whatever was the right remediation when the process started is no longer the right remediation afterward.
In particular, I am thinking that when you are connected to a content-filtered network that some remediations may be forced by state actors, or other local policy, but the same situation might not occur when switching to some other geography SIM/LTE connection.

**Comment by dthaler** [comment]
Filed a PR to elaborate on the time, and why a different mechanism like timestamps might be more appropriate in such cases.

As for "it might be that whatever was the right remediation when the process started is no longer the right remediation afterward". This is always true and is unrelated to the freshness mechanism or even the use of TEEP.   If you inherently cannot get a remediation right away, it may no longer be right by the time you get it.  In that case, the process just starts over.

**Comment by dthaler** [comment]
Fixed in draft-11
