### ISSUE TITLE
Hackathon 115: EAT, distinguish Evidence or Attestation Result

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#263]
We are in the middle of considering how the TAM would process EAT in the QueryResponse.

We would like to have an indication of whether the contents of the EAT is Evidence or Attestation Result.
When the TAM receives the EAT in QueryResponse and if the EAT has the Attestation Result of the TEEP Agent, then the TAM must parse the EAT and process the credibility of the TEEP Agent.
If the EAT contains Evidence, then the TAM would be simply passing the Evidence to the appropriate Verifier without parsing the contents of the EAT only if the TAM could distinguish the EAT is Evidence without parsing it.

Having the indication of Evidence or Attestation Result would make the implementation of the TAM simpler.

This might be a different topic, there is scenario of EAT in chapter `D.2.1.  CBOR Diagnostic Notation / eat-claim-set = /` which is example of Evidence.
I would like to add the scenarios of when it is Attestation Result, is there a place where I should look in EAT/RATS draft?

**Comment by mcd500** [comment]
The 7.1.1. describes how to distinguish Evidence or an Attesation Result,

>    If a QueryResponse message is received that contains an attestation-
>    payload, the TAM checks whether it contains Evidence or an Attesation
>    Result by inspecting the attestation-payload-format parameter.  The
>    media type defined in Section 5 indicates an Attestation Result,
>    though future extensions might also indicate other Attestation Result
>    formats in the future.  Any other unrecognized value indicates
>    Evidence.  If it contains an Attesation Result, processing continues
>    as in Section 7.1.1.1.

that being said, the description of the attestation-payload-format in 4.3. is

>    attestation-payload-format
>       The attestation-payload-format parameter indicates the IANA Media
>       Type of the attestation-payload parameter, where media type
>       parameters are permitted after the media type.  The absence of
>       this parameter indicates that the format is "application/eat-cwt;
>       profile=https://datatracker.ietf.org/doc/html/draft-ietf-teep-
>       protocol-10" (see [I-D.lundblade-rats-eat-media-type] for further
>       discussion).  (RFC-editor: upon RFC publication, replace URI above
>       with "https://www.rfc-editor.org/info/rfcXXXX" where XXXX is the
>       RFC number of this document.)  It MUST be present if the
>       attestation-payload parameter is present and the format is not an
>       EAT in CWT format with the profile defined below in Section 5.

which is more focused on either CWT or JWT and etc and not for identifying 
EAT format containing Evidence or an Attestation Result.

**Comment by dthaler** [comment]
If it's a type the TAM recognizes as an Attestation Result, it's an Attestation Result.  Otherwise it's treated as Evidence.

**Comment by mcd500** [comment]
@dthaler 
The intention of this issue is because that one of team in Japan is starting the implementation of the Passport model of the Remote attestation on TEEP.
 
We are expecting to finalize the details during the hackathon at IETF115 for the CDDL of Attestation Result in the EAT.
I just changed the title to be clear.

**Comment by mcd500** [comment]
For the TAM to recognize the EAT as an Attestation Result without parsing the EAT,these are the ideas we have right now.

Using kid in the cose header.
From the cose draft, https://cose-wg.github.io/cose-spec/ the kid in the cose header is able to read before parsing the EAT format.
This is assuming the TAM would know which TEEP-Agent requires a Background-Check Model and which are Passport Model. Then the EAT format in COSE-sign would have different kid in the cose header to distinguish which kid is Background-Check Model and just ok to relay the EAT format to the correct verifier.

Add additional id in the attestation-payload-format.
The benefit of this approach is it able to find if the EAT contains the Evidence or Attestation Result even if the EAT format is not using the COSE.

We could discuss it at the IETF 115.

**Comment by dthaler** [comment]
My view is that the TEEP profile id in the TEEP protocol spec should just be defined as being for Attestation Results, since that's all TEEP cares about seeing.

**Comment by kentakayama** [comment]
It is good to define two EAT profiles: one is for Evidence, the other one is for Attestation Result.
I think we can distinguish them with profile tags in attestation-payload-format like this.
```
/ Evndence /
attestation-payload-format = "application/eat-cwt; profile=tag:evidence.teep.ietf.org"

/ Attestation Result /
attestation-payload-format = "application/eat-cwt; profile=tag:ar4si.teep.ietf.org"
```
https://datatracker.ietf.org/doc/html/draft-lundblade-rats-eat-media-type-00#section-4

Does anyone know about EAT profile tag?

**Comment by dthaler** [comment]
I think it's fine to have separate profiles for evidence vs attestation results, but ar4si as specified in draft-ietf-rats-ar4si is not sufficient for TEEP, we need a profile that supports TEEP.   So the one in the doc now is really an attestation result profile, and we don't have an evidence profile right now per se.

**Comment by dthaler** [comment]
@mcd500 any changes needed or can this be closed now?

**Comment by kentakayama** [comment]
I think we need no modifycation.

The `attestation-payload-format` is enough powerful to distinguish them. TEEP Agent and TAM developers MAY create their EAT Profiles that distinguish Evidence or Attestation Result, and tell the TAM how the attestation-payload should be treated as Evidence (by specifying a Verifier, protocol, etc.) or Attestation Result (by specifying an Appraisal Policy, etc.) with profile field. The attestation-payload-format MAY indicate not only EAT-CWT but also other attestation-payload such as EAT-JWT, existing attestation data formats in products, and any other user-defined formats.

**Comment by mcd500** [comment]
Discussion at the ietf 115 hackathon and conclusion was the current draft is fine and do not have to change on this item.
I will change the label to this issue.

**Comment by mcd500** [comment]
I will add the link to the description in the hackathon slide once it is uploaded.
