### ISSUE TITLE
`profile` -> `eat_profile`

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-teep/teep-protocol#265]
In version -01 of the EAT media types document we just changed the media type parameter name from `profile` to `eat_profile`.

For more context see
* https://www.ietf.org/archive/id/draft-ietf-rats-eat-media-type-01.html#section-3
* https://github.com/ietf-rats-wg/draft-eat-mt/issues/4 and
* https://github.com/ietf-rats-wg/draft-eat-mt/pull/11

**Comment by dthaler** [comment]
Fixed in draft-11
