### ISSUE TITLE
Is Complete CDDL appendix normative?

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#269]
Typically an "appendix" is by definition informative not normative.

https://www.rfc-editor.org/rfc/rfc8610#appendix-B is an example of a notable exception where an appendix explicitly states "This appendix is normative."

In the TEEP protocol spec we have a "Complete CDDL" appendix.  Is it normative like the above is?  Or informative like is the default?

Issue #262 is evidence that there can be contradictions between the CDDL snippets in the appendix vs in the body.  So if a contradiction is later found, which one takes precedence?   So far I have been operating on the assumption that the appendix is informative and the body takes precedence, but either way it would be good to say informative or normative at the top of that appendix.

**Comment by mcd500** [comment]
I prefer informative.

**Comment by dthaler** [comment]
Fixed in draft-11
