### ISSUE TITLE
Hackathon 115: SUIT_Envelope vs SUIT_Envelope_Tagged

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#273]
(Splitting this issue off #262 which was just to resolve the contradiction)

Ken wrote:

> I think using + bstr .cbor SUIT_Envelope_Tagged is better because:
> 
> - we can distinguish SUIT Manifest from other CBOR-based manifests (currently there is no such manifest though)
> - the tag consumes only 2 bytes
> - existing SUIT Manifest generator (suit-tool by Arm and libcsuit by me) creates tagged manifest binary

Dave wrote:

> No other format is currently permitted. SUIT_Envelope in the production requires it to be SUIT.
> Are you saying you think we should allow for other manifest formats?
> That's possible if we change lots of other things in the spec, but would be a big enough change I wouldn't do it without a WG discussion on that topic first. Hence at present there is no need for SUIT_Envelope_Tagged.
> 
> We can save 2 bytes per manifest by not adding the tag which is not needed, just like we removed the COSE tag.
> 
> That's an issue for the suit-tool to fix by adding an appropriate option.

Akira wrote:

> The main reason we decided to not to use COSE Tags on TEEP-Message was that we did not have the bandwidth for creating a new tag number and register to IANA registry that time.
> 
> The SUIT Manifest already has an assigned tag by the effort of SUIT working group, so I am perfectly fine using the tag only for the SUIT Manifest which do not effect on implementation which uses a tag on SUIT manifest and not using any tag on entire TEEP massage.

**Comment by mcd500** [comment]
We have discussed during the ietf 115 hackathon to use untagged CBOR Envelope on both SUIT Manifests and TEEP Messages.
No changes in the body of the draft.
Some examples in Appendix have tagged SUIT_Envelopes which have to be updated later.

**Comment by kentakayama** [comment]
As Hannes mentioned above, there is no SUIT_Envelope_Tagged example in the draft.
In the hackathon both libcsuit and suit-tool were updated to genarate untagged SUIT manifest.

**Comment by mcd500** [comment]
@dthaler 
Ugh, found one more place which had the tag left.
Just made one more PR.
https://github.com/ietf-teep/teep-protocol/pull/293
Please review and merge.

This removing cbor tag thing, took a lot of detail concentration.

**Comment by dthaler** [comment]
Fixed in draft -12
