### ISSUE TITLE
Hackathon 115: EAT manifests claim in TEEP profile

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#285]
EAT spec says: “A [[SUIT.Manifest](https://www.ietf.org/archive/id/draft-ietf-rats-eat-17.html)] may be used as a manifest.”
```
manifest-format = [
    content-type:   coap-content-format,
    content-format: JC< $manifest-body-json,
                        $manifest-body-cbor >
]
```
What CBOR object in body?   Propose: SUIT_Reference

What coap content format?   Propose: new value
* More specific than just application/cbor
* To be added in draft-ietf-suit-reports

**Comment by mcd500** [comment]
The PR https://github.com/ietf-teep/teep-protocol/pull/284 merged, which is for the first question in the issue that SUIT_Reference in the CBOR object body.

**Comment by mcd500** [comment]
@dthaler 
Hi, this format of the SUIT_Reference.
```
SUIT_Reference = {
    suit-report-manifest-uri  => tstr,
    suit-report-manifest-digest => SUIT_Digest,
}
```
The SUIT_Reference must contain the manifest-uri which is a bit difficult for when using the manifest embedded only inside the TEEP message.
Would it be a way to have using suit component ID for this purpose?
