### ISSUE TITLE
Hackathon 115: SUIT reports can contain sensitive information

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#286]
IETF 114 slide on issue #234 asked:
> Q: can SUIT reports be encrypted?

Currently the Privacy Considerations section of the TEEP protocol draft says nothing about the sensitivity of SUIT reports, and the TEEP protocol does not do encryption.

As a related issue EAT tokens can also contain sensitive information.  Draft -11 says

> To lower the
privacy implications the TEEP Agent MUST present its
attestation payload only to an authenticated and authorized TAM and when using
an EAT, it SHOULD use encryption as discussed in {{I-D.ietf-rats-eat}}, since
confidentiality is not provided by the TEEP protocol itself and
the transport protocol under the TEEP protocol might be implemented
outside of any TEE.

But the EAT profile section says:
> * COSE/JOSE Protection: See {{ciphersuite}}.

And the cipher suite section referenced is for the TEEP protocol and just does signing, not encryption.  This seems like a contradiction.

**Comment by mcd500** [comment]
There are two ways of coping when SUIT_Reports contain sensitive information.
1) Encrypt entire TEEP Messages
2) Encrypt SUIT_Reports in the TEEP Messages

Also, the TC consists of Trusted Application and/or Personalization Data, so many use cases of Personalization Data would contain sensitive information as well.

Both cases could be solve by encrypting the TC (with Personalization Data) and SUIT_Reports.
Then it require wrapping SUIT_Reports with COSE according to the draft 
"Encrypted Payloads in SUIT Manifests"
https://datatracker.ietf.org/doc/draft-ietf-suit-firmware-encryption/

In this case assuming the TC is embedded in SUIT-Manifest.

**Comment by dthaler** [comment]
Proposal in [IETF 115 slides](https://datatracker.ietf.org/meeting/115/materials/slides-115-teep-teep-protocol-00): 
> * Leave it to draft-ietf-suit-reports to specify encryption details
> * Add privacy consideration text to teep-protocol draft and refer to draft-ietf-suit-reports for more detailed discussion

Ensuring discussion from [meeting minutes](https://datatracker.ietf.org/meeting/115/materials/minutes-115-teep-202211091500-00):

> Add privacy considerations
> Russ Housley: heard something different. Lots of places they
> want this in plaintext.
> Thaler: if sneaker netting, who's responsbility is it to encrypt
> that
> Bredan: You want a statement in security requirements of
> suit-report that says if there is anything senstive you need to
> encrypt that
> Brendan: MTI document, is only for constrained device update
> only its covered in there.
> Thaler: Then should this be covered in the TEEP protocol?
> Brendan: Yes
> Thaler: Any objections to having it in TEEP not in SUIT-report?
> [none heard]

**Comment by dthaler** [comment]
For the EAT portion of this issue...

[IETF 115 slides](https://datatracker.ietf.org/meeting/115/materials/slides-115-teep-teep-protocol-00) say:
> • Sign and then encrypt EAT?
> • Which cipher suite for encryption do we specify in the EAT profile?
> • Is it the same as for SUIT reports or might it be different since the sender is different?

Ensuring discussion from [meeting minutes](https://datatracker.ietf.org/meeting/115/materials/minutes-115-teep-202211091500-00):

> A good ciphersuite is the one already implemented
> Destination if SUIT report and EAT are different - one goes to verifier _(should say TAM)_, other goes to verifier
> Thaler: Recommends they should be the same, but still need to pick something
> Encryption algorithms havbe not ebeen discussed
> Brendan: Should we use different ones from the MTI doc in SUIT? Some implementor already has hard requirement for RSA.
> Would be inclinde to ask what they require as they are not in the draft.
> Brendan - this is not about key exchange just bulk encryption. You don't need to deal with out of order arrival of data. This should not be an issues - use the AEADs. If you can afford e.g CCM that is the way to go.
> Russ, Hannes: +1 on that recommendation

**Comment by mcd500** [comment]
The consensus is that encrypting SUIT and EAT are ok.
Perhaps which MTI to choose is next?

**Comment by hannestschofenig** [comment]
I wonder whether it is the task of the TEEP protocol to specify how SUIT reports should be encrypted. IMHO it is really the job of draft-ietf-suit-report to provide an answer to this since you could conceptually re-use the work on firmware encryption but it needs to be repurposed to the new structure provided by the SUIT report draft.

**Comment by hannestschofenig** [comment]
Regarding the use of EAT encryption capabilities can be used (although the EAT specification does not narrow the choices down). We could limit the choices to those in the SUIT firmware encryption draft. However, there is a practical challenge: Who is going to do the encryption? Normally, one would assume that the entity creating the EAT token (which also signs it) performs the encryption. Today, this is not done anywhere. Hence, this encryption has to be accomplished by the TEEP Agent. The TEEP Agent needs to know the party it is encrypting the message to. Who is that party? Is it the TAM or, more likely, the Verifier? (FWIW who is the party processing the SUIT reports? Is this the TAM?)

**Comment by hannestschofenig** [comment]
Including a mandatory ciphersuite for encryption, as done with https://github.com/ietf-teep/teep-protocol/pull/311/, sounds reasonable but misses the challenging aspect of key distribution.

**Comment by dthaler** [comment]
> I wonder whether it is the task of the TEEP protocol to specify how SUIT reports should be encrypted. IMHO it is really the job of draft-ietf-suit-report to provide an answer to this since you could conceptually re-use the work on firmware encryption but it needs to be repurposed to the new structure provided by the SUIT report draft.

See the minutes text quoted in comments earlier in this issue where the meeting consensus was that it was the task of the TEEP protocol not the SUIT reports document.  My PR just intends to follow the meeting consensus.

**Comment by dthaler** [comment]
> Regarding the use of EAT encryption capabilities can be used (although the EAT specification does not narrow the choices down). We could limit the choices to those in the SUIT firmware encryption draft.

The meeting consensus seemed to be using an AEAD CCM algorithm, which is what my PR intended to follow.  If you want to suggest an alternative, please do so on the TEEP and SUIT lists.  I have no strong opinion myself.

> Who is going to do the encryption? Normally, one would assume that the entity creating the EAT token (which also signs it) performs the encryption. Today, this is not done anywhere. Hence, this encryption has to be accomplished by the TEEP Agent. 

Right.

> The TEEP Agent needs to know the party it is encrypting the message to. Who is that party? Is it the TAM or, more likely, the Verifier?

Yes the Verifier.

>  (FWIW who is the party processing the SUIT reports? Is this the TAM?)

Yes the TAM.

**Comment by mcd500** [comment]
It would be easier for the TEEP-Agent could use the same algorithms for both SUIT/EAT and TEEP.

@bremoran is writing `Mandatory-to-Implement Algorithms for Creators and Consumers of Software Update for the Internet of Things manifests` at here.
https://datatracker.ietf.org/doc/draft-moran-suit-mti/

Since TEEP's mandatory signing algorithms are ECDSA/ES256 and EdDSA, it would be nice to have signing profiles for ECDSA/ES256 and EdDSA in draft-moran-suit-mti.

For symmetric encryption, I prefer to have AES-GCM version of suit-sha256-hmac-a128-ccm in the suit-mti, since GCM and preferred over CCM here.

The AEAD CCM mentioned by Dave is not in the suit-mti at the moment, and also prefer AEAD GCM for the same reason above.

For asymmetric encryption, I prefer having ECDSA version of suit-sha256-eddsa-ecdh-es-chacha-poly to match the MTI in TEEP.

**Comment by mcd500** [comment]
By the way, does anyone know which downloadable cddl file would have these defined?
eat-suit-cipher-suite
eat-suit-cipher-suite-encrypt0-aesccm
...

They are required for the cddl syntax check.

**Comment by dthaler** [comment]
> It would be easier for the TEEP-Agent could use the same algorithms for both SUIT/EAT and TEEP.

Not possible without encrypting the entire TEEP message, since TEEP only uses signing algorithms, whereas SUIT/EAT need encryption algorithms.

> @bremoran is writing `Mandatory-to-Implement Algorithms for Creators and Consumers of Software Update for the Internet of Things manifests` at here. https://datatracker.ietf.org/doc/draft-moran-suit-mti/

Sounds like a good informative reference, I can update my PR.

> Since TEEP's mandatory signing algorithms are ECDSA/ES256 and EdDSA, it would be nice to have signing profiles for ECDSA/ES256 and EdDSA in draft-moran-suit-mti.
> 
> For symmetric encryption, I prefer to have AES-GCM version of suit-sha256-hmac-a128-ccm in the suit-mti, since GCM and preferred over CCM here.

Sounds like feedback for that document instead of this one.

> The AEAD CCM mentioned by Dave is not in the suit-mti at the moment, and also prefer AEAD GCM for the same reason above.

CCM was what I took to be the consensus at IETF 115 so I put that in.  Feel free to argue for GCM in the meeting or on the list.  I have no strong opinion here as it's outside my area of expertise.

> For asymmetric encryption, I prefer having ECDSA version of suit-sha256-eddsa-ecdh-es-chacha-poly to match the MTI in TEEP.

**Comment by dthaler** [comment]
> By the way, does anyone know which downloadable cddl file would have these defined? eat-suit-cipher-suite eat-suit-cipher-suite-encrypt0-aesccm ...
> 
> They are required for the cddl syntax check.

They are part of check-draft-ietf-teep-protocol.cddl which is generated when you run make in the cddl directory of this repo.

**Comment by dthaler** [comment]
> Including a mandatory ciphersuite for encryption, as done with #311, sounds reasonable but misses the challenging aspect of key distribution.

TEEP uses TEEP with [I-D.rats-concise-ta-stores] to update persistent keys in the TEEP and TEEP Agent.
After doing a bit more reading I now agree with Akira...

The TEEP architecture already requires the TEEP Agent to have the TAM's public key, which my understanding is required by HPKE but Key Wrap would require a separate key which isn't mentioned in the TEEP Architecture.
And the suit-mti document's [suit-sha256-es256-hpke-a128gcm](https://www.ietf.org/archive/id/draft-moran-suit-mti-02.html#name-current-asymmetric-mti-prof) and [suit-sha256-ed256-hpke-a128gcm](https://www.ietf.org/archive/id/draft-moran-suit-mti-02.html#name-current-asymmetric-mti-profi) profiles also use ES256 and EdDSA which we already require in TEEP.

So I will change my PR to hopefully align with this in the hopes we can get consensus at IETF 116.  I.e., leave Key Wrap to a future TEEP extension since it's more complicated to specify than the HPKE profiles.

**Comment by mcd500** [comment]
> > By the way, does anyone know which downloadable cddl file would have these defined? eat-suit-cipher-suite eat-suit-cipher-suite-encrypt0-aesccm ...
> > They are required for the cddl syntax check.
> 
> They are part of check-draft-ietf-teep-protocol.cddl which is generated when you run make in the cddl directory of this repo.

Oh, I wrote the comments for this part here.
https://github.com/ietf-teep/teep-protocol/pull/313/files#r1132035985
https://github.com/ietf-teep/teep-protocol/pull/313/files#r1132037786

**Comment by mcd500** [comment]
> > Since TEEP's mandatory signing algorithms are ECDSA/ES256 and EdDSA, it would be nice to have signing profiles for ECDSA/ES256 and EdDSA in draft-moran-suit-mti.
> > For symmetric encryption, I prefer to have AES-GCM version of suit-sha256-hmac-a128-ccm in the suit-mti, since GCM and preferred over CCM here.
> 
> Sounds like feedback for that document instead of this one.

Yes, it is my comment on the https://datatracker.ietf.org/doc/draft-moran-suit-mti/.

I will post my comment on the suit mailing list.

**Comment by bremoran** [comment]
> I wonder whether it is the task of the TEEP protocol to specify how SUIT reports should be encrypted. IMHO it is really the job of draft-ietf-suit-report to provide an answer to this since you could conceptually re-use the work on firmware encryption but it needs to be repurposed to the new structure provided by the SUIT report draft.

Is it? I'm not convinced. SUIT provides encryption because of an at-rest security requirement that cannot be provided by, e.g., TLS. Do SUIT reports need to be staged somewhere? Do they need to be retained by an untrusted party?

Why is TLS not an adequate answer for SUIT reports?

**Comment by bremoran** [comment]
I'm a little confused by some of this discussion. 
>Since TEEP's mandatory signing algorithms are ECDSA/ES256 and EdDSA, it would be nice to have signing profiles for ECDSA/ES256 and EdDSA in draft-moran-suit-mti.

Is suit-sha256-es256-hpke-a128gcm/suit-sha256-ed256-hpke-a128gcm not appropriate for this? It gives you ES256/EdDSA signing? I realise that it lists HPKE but that does NOT imply that encryption is mandatory, only that, if encryption is used, it must be HPKE/AES128GCM.

Let's revisit AESCCM vs AESGCM discussion of the Symmetric MTI profile at the SUIT meeting. My reasoning was simply that GCM requires the Gallois Field Multiplication code, whereas CCM reuses the AES block, so it should be smaller footprint. Since the Symmetric MTI profile is intended for the smallest devices, it makes sense to keep the footprint small.

**Comment by mcd500** [comment]
> > Since TEEP's mandatory signing algorithms are ECDSA/ES256 and EdDSA, it would be nice to have signing profiles for ECDSA/ES256 and EdDSA in draft-moran-suit-mti.
> 
> Is suit-sha256-es256-hpke-a128gcm/suit-sha256-ed256-hpke-a128gcm not appropriate for this? It gives you ES256/EdDSA signing? I realise that it lists HPKE but that does NOT imply that encryption is mandatory, only that, if encryption is used, it must be HPKE/AES128GCM.

Nothing special, I just thought there would be two types of profiles coming to your MTI draft, one for only signing and another for signing + encryption.

Did not know you were having the idea of using the cddl defined in the COSE for this purpose as you mentioned in the mailing list. 

If the TEEP will not be using encrypting SUIT/EAT, then the developer would like to include one hash algorithm and one signing algorithm, such as SHA256 + ECDSA or SHA256 + EdDSA for the TEEP in the constrained device. 

I remember that there is the header in mbedtls which algorithms would like to be left in the library when building mbedtls from source. It will make the developer happy with the small footprint of the library. 

The ECDSA and EdDSA both require specifying which hash algorithm among many to use, so the profile for having the explicit combination might easier for the developer to what to do.

It might be the COSE cddl role to specify the combination of the the hash algorithm and the signing algorithm.

**Comment by dthaler** [comment]
Fixed in draft -12
