### ISSUE TITLE
Relationship between TEEP EAT profile and AR4SI

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#289]
What is the relationship?  The TAM needs an EAT using TEEP's EAT profile, whereas the eventual Relying Party may need Attestation Results in a different format, like AR4SI.

Option 1: TAM is not an intermediary in the verifier flow
Option 2: TAM is an intermediary and separately requests TEEP profile vs AR4SI in separate exchanges
Option 3: TAM is an intermediary and requests both in the same Attestation Result, such as putting an AR4SI EAT inside a claim in the TEEP EAT

**Comment by hannestschofenig** [comment]
I think the use of attestation based on the drawings above is too complex. 

Here is how I see this working:
![grafik](https://user-images.githubusercontent.com/1016643/202198943-3dcc9769-1f64-41d0-a16b-16a701942ae6.png)

**Comment by dthaler** [comment]
[Minutes from IETF 115](https://datatracker.ietf.org/meeting/115/materials/minutes-115-teep-202211091500-00)

- Relationship between TEEP EAT profile and AR4SI (slide 18)
  - Discussed 5 options, None ideal
  - Thaler - prefernece is for option 4 or 5.
  - Call for feedback.
  - Penglin: TAM can be verifier (collapse roll) - this will simplify
    - Thaler - dont want to force it, but allow yes.
  - Akira Tsukamoto: prefer option 4 between 4 and 5; easier to update draft than too. How implement on SGX, not clear/informative enough in the draft.
  - Hannes: Do we need to cover passport and background check. Nobody forcing to cover full architecture from RATS
    - Thaler: TAM is a specific Relying Party (background checks). Things more complex when using passport checks. Need to accomodate both. TAM could send two queries to the verifier, but will need different nonces (timestamp may help avoid it)
