### ISSUE TITLE
CDDL validation failure on system-property-claims

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#291]
It is mandatory to insert `$$SUIT_Parameters` after the component id.
Should we do that or ask @bremoran to change the system-property-claims?

- [system-property-claims in SUIT Report CDDL](https://github.com/suit-wg/suit-report/blob/main/draft-ietf-suit-report.cddl#L26-L29) says
```
system-property-claims = {
  system-component-id => SUIT_Component_Identifier,
  + $$SUIT_Parameters,
}
```

- [QueryResponse CDDL](https://github.com/ietf-teep/teep-protocol/blob/master/draft-ietf-teep-protocol.cddl#L95) says
```
    ? tc-list => [ + system-property-claims ],
```

- [QueryResponse example](https://github.com/ietf-teep/teep-protocol/blob/master/cbor/query_response.diag.txt#L11-L16) says
```
    / tc-list / 8 : [
      {
        / system-component-id / 0 : [ h'0102030405060708090A0B0C0D0E0F' ]
        / XXX: one or more $$SUIT_Parameters must be here /
      },
      {
        / system-component-id / 0 : [ h'1102030405060708090A0B0C0D0E0F' ]
      }
    ]
```

**Comment by mcd500** [comment]
@bremoran, I talked with Ken today.

Changing from 
```
system-property-claims = {
  system-component-id => SUIT_Component_Identifier,
  + $$SUIT_Parameters,
}
```
to
```
system-property-claims = {
  system-component-id => SUIT_Component_Identifier,
  * $$SUIT_Parameters,
}
```
would suffice the usage of system-property-claims in TEEP.
Then the SUIT_Parameters will not be mandatory in system-property-claims.

I will make the PR at the SUIT_Report.

**Comment by mcd500** [comment]
Copying my comment here from the https://github.com/suit-wg/suit-report/pull/5

In the example of QueryResponse in TEEP protocol,
https://github.com/ietf-teep/teep-protocol/blob/master/cbor/query_response.diag.txt#L11-L16
two TCs are listed in the tc-list.
Will update the example to have one of the TC in the tc-list to have component ID supplied with version information as a SUIT_Parameters and another TC having component ID and digest value as a SUIT_Parameters.
So system-property-claims having at least one SUIT_Parameters in the system-property-claims is perfectly fine.

**Comment by kentakayama** [comment]
@mcd500 @dthaler 
I've quickly updated QueryResponse message example.
If this fine with you, I'll create a PR.

```
/ query-response = /
[
  / type: / 2 / TEEP-TYPE-query-response /,
  / options: /
  {
    / token / 20 : h'A0A1A2A3A4A5A6A7A8A9AAABACADAEAF',
    / selected-cipher-suite / 5 : [ [ 18, -7 ] ] / Sign1 using ES256 /,
    / selected-version / 6 : 0,
    / tc-list / 8 : [
      {
        / component-id / 16 : [ h'0102030405060708090A0B0C0D0E0F' ],
        / suit-parameter-image-digest / 3: << [
          / suit-digest-algorithm-id / -16 / SHA256 /,
          / suit-digest-bytes / h'a7fd6593eac32eb4be578278e6540c5c09cfd7d4d234973054833b2b93030609'
            / SHA256 digest of tc binary /
        ] >>
      },
      {
        / component-id / 16 : [ h'1102030405060708090A0B0C0D0E0F' ],
        / suit-parameter-version / 28 : [1, 0, 0] / ver 1.0.0 /
      }
    ]
  }
]
```

**Comment by kentakayama** [comment]
@mcd500 @dthaler 
Resolved with this [commit](https://github.com/ietf-teep/teep-protocol/pull/290/commits/4995eb1fae28ed7b3c203f0cdf4530eee0a511db).

**Comment by dthaler** [comment]
Fixed in draft -12
