### ISSUE TITLE
Error return for QueryResponse 

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#297]
Should we add an option to return teep-error value from the TAM? 

This issue is related to https://github.com/ietf-teep/teep-protocol/issues/245. 

Currently, when TAM receives the QueryResponse, only sending Update message is allowed which most of the cases it is ok. 

Secom is implementing the Passport model on the TEEP-Agent side and will be including Attestation Result in the QueryResponse. 

In this case if the TAM must reject the QueryResponse based on the content of the Attestation Result, it must wisely reply with Update message. 

 

This might be IETF 116 topic. Having a way to return error message in this case might be useful.

**Comment by dthaler** [comment]
Why not just do an Update?   The TAM's job is the manage the TEE so if the TEE is not in compliance when would you want to do something other than bring it into compliance?

**Comment by mcd500** [comment]
Sure, as we discussed at the IETF 115, TAM performing the Update of the Agent and bringing the Agent to be compliant is the correct way. 

For the Agent having very strong hardware support can make the Agent to be compliant even the Agent is compromised by an attacker. 

I felt in some cases having an option to TAM to give up bringing the Agent to be compliant would be useful. Some Agent may not have a strong hardware support and may be difficult to correctly make the Agent compliant after it is compromised. 

I remember when I cracked some of software by patching with binary editor and did not want the vendors sever to fix it by the update, I used to make it return the version number with the same latest version number. In this case, it is possible for the TAM to wisely update the Agent and bring it back to the compliant state, but it may be ok just to give up and ignore the Agent for the further Update until the maintenance personnel fix the Agent and the meantime, mark it as compromised in the TAM. 

 

This is the format of the cddl I had in my mind. 

``` 

update = [ 
  type: TEEP-TYPE-update, 
  options: { 
    ? token => bstr .size (8..64), 
    ? unneeded-manifest-list => [ + SUIT_Component_Identifier ], 
    ? manifest-list => [ + bstr .cbor SUIT_Envelope ], 
    ? attestation-payload-format => text, 
    ? attestation-payload => bstr, 
    * $$update-extensions, 
    * $$teep-option-extensions 
  } 

  err-code: 0..23 
] 

```

**Comment by dthaler** [comment]
> I felt in some cases having an option to TAM to give up bringing the Agent to be compliant would be useful. Some Agent may not have a strong hardware support and may be difficult to correctly make the Agent compliant after it is compromised.

I think that's a fair argument.

> This is the format of the cddl I had in my mind.

I don't see a reason to make an err-code be mandatory, or to include it in case of no error.
Why not move it into the options and treat it like one of the $$update-extensions?

**Comment by mcd500** [comment]
Thanks, I have made the PR for this. https://github.com/ietf-teep/teep-protocol/pull/298

**Comment by dthaler** [comment]
Fixed in draft -12
