### ISSUE TITLE
IETF116: Change HPKE to ECDH

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#326]
to match draft-ietf-suit-mti as discussed in the TEEP WG meeting at IETF 116

**Comment by mcd500** [comment]
The https://github.com/ietf-teep/teep-protocol/pull/331 is merged.

**Comment by mcd500** [comment]
The https://github.com/ietf-teep/teep-protocol/pull/332 is also merged.

**Comment by dthaler** [comment]
Fixed in draft -13
