### ISSUE TITLE
[IESG submission] Attesting TAM from Agent in the architecture draft is not in the TEEP protocol draft

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#341]
In the TEEP architecture draft Section 9.5 to address TAM compromise, which suggests to use remote
attestation of the TAM from the TEEP Agent to prove trustworthiness.

Currently, we do not provide this feature in the TEEP protocol.

**Comment by mcd500** [comment]
Fixed in the PR https://github.com/ietf-teep/teep-protocol/pull/335

**Comment by dthaler** [comment]
Fixed in draft-15
