### ISSUE TITLE
Hackathon 117: Returning err-code and err-msg in Update message

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#347]
The draft permits this due to resolution for issue #297, which was originally intended for the use case of "if the TAM must reject the QueryResponse based on the content of the Attestation Result".
While the err-code and err-msg fields were added the TAM behavior section still doesn't talk about them.

Section 7.1.1.1 "Handling an Attestation Result" says:
> Attestation failed. This indicates that the rest of the information in the QueryResponse cannot necessarily be trusted, as the TEEP Agent may not be healthy (or at least up to date). In this case, the TAM **can attempt to use TEEP to update any Trusted Components** (e.g., firmware, the TEEP Agent itself, etc.) needed to get the TEEP Agent back into an up-to-date state that would allow attestation to succeed.

and
> If no Trusted Components need to be installed, updated, or deleted, but the QueryRequest included Evidence, the TAM MAY (e.g., based on attestation-payload-format parameters received from the TEEP Agent in the QueryResponse) still send an Update message with no SUIT Manifests, to pass the Attestation Result back to the TEEP Agent.

It doesn't mention anything about sending error information back to the TEEP Agent.

Also, section 7.1.1 (Handling a QueryResponse Message) says:
> If a QueryResponse message is received, the TAM verifies the presence of any parameters required based on the data-items-requested in the QueryRequest, and also validates that the nonce in any SUIT Report matches the token sent in the QueryRequest message if a token was present. If these requirements are not met, the TAM drops the message. It may also do additional implementation specific actions such as logging the results.

It doesn't say that an Update can be sent with error information, but then it says it "may also do additional implementation specific actions such as logging the results".  One interpretation is that it could send an Update message with error information.

We should probably be clearer about whether this is required, recommended, allowed, or disallowed.

**Comment by mcd500** [comment]
I agree.
I talked with Dave over the call.

**Comment by ko-isobe** [comment]
Commented for this proposal in #348.

BTW, the second quoted section in this issue might be wrong:
```
 but the QueryRequest included Evidence,
```
Is this QueryResponse? From my understand, this sentence describes BC model, which TAM receives Agent's Evidence by QResponse,  pass it to Verifier and TAM sends back AR to Agent via Update message.

**Comment by dthaler** [comment]
> Commented for this proposal in #348.
> 
> BTW, the second quoted section in this issue might be wrong:
> 
> ```
>  but the QueryRequest included Evidence,
> ```
> 
> Is this QueryResponse? From my understand, this sentence describes BC model, which TAM receives Agent's Evidence by QResponse, pass it to Verifier and TAM sends back AR to Agent via Update message.

Fixed, thanks!

**Comment by dthaler** [comment]
Fixed in draft-16
