### ISSUE TITLE
Hackathon 117: kid in EAT profile refers COSE Key Thumbprint

### ISSUE THREAD

**Issue by ko-isobe** [ietf-teep/teep-protocol#349]
In TEEP EAT profile (in Section 5), kid is defined as:
```
Key Identification: COSE Key ID (kid) is used, where the key ID is the hash of a public key (where the public key may be used as a raw public key, or in a certificate). 
See Section 7.1.1.1 and Section 7.2.1.1 for discussion on the choice of hash algorithm.
```

In this IETF, @hannestschofenig and I submitted [COSE Key Thumbprint I-D](https://datatracker.ietf.org/doc/draft-isobe-cose-key-thumbprint/), which defines the calculating method for identifying COSE Key object by key parameters.
This definition and our I-D are similar so we can make the definition by referring the I-D.
TEEP Protocol basically uses CBOR and COSE. Even though public keys can be passed by certificates, each implementation has CBOR and COSE and can calculate the COSE Key thumbprint values.
So it may not be harmful to limit the kid value from calculating from COSE Key only.

(The I-D doesn't cover the choosing hash algorithms. If we employ the referring, we can keep the deciding of hash algorithms as current draft.)

**Comment by dthaler** [comment]
Fixed in draft-16
