### ISSUE TITLE
Clarify how attestation information is kept confidential

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#35]
The security considerations section says this about the attestation information:
>  This uniqueness may raise privacy concerns.  To lower the
>  privacy implications the TEEP Agent MUST present its attestation
>  information only to an authenticated and authorized TAM.
But what it doesn’t say (and I think should point out) is the point that encryption can be provided by payload security, i.e., draft-ietf-rats-eat provides encryption via JOSE/COSE encryption, and the TEEP protocol just carries such encrypted JOSE/COSE objects without the TEEP protocol having to encrypt TEEP messages.

Currently the only mention of encryption in that doc is about TA binaries, which is in the opposite direction (TAM to Agent) than the one relevant here.

In contrast draft-ietf-teep-opentrustprotocol had text about encrypting device state information, which generates questions about why draft-ietf-teep-protocol does not.   Need to elaborate in the text as to why, i.e., because it's part of the draft-ietf-rats-eat and just carried by the TEEP protocol.

**Comment by hannestschofenig** [comment]
This issue should have been closed already given that the text has been published in -03.

**Comment by dthaler** [comment]
TEEP leaves it to the WG chairs to close issues, we just mark it as ready to close.
