### ISSUE TITLE
Do we need to refer SUIT Report as normative?

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#355]
As SUIT Report can be embedded into measres claim of EAT, the attestation-payload is also appropriate option to carry it.

There are some discussion points:
- Do we refer SUIT Report as normative or informative?
- Can we remove suit-reports option?
  - And then, from which message? {QueryRequest and QueryResponse messages, or all messages}

I prefer option 1 but it might be a drastic change. The next best is option 2.
- option 1: Remove suit-reports option from all messages
  - Mentioning about SUIT Reports as one of claims of attestation-payload, and refer it as informative document
  - Change the data type of attestation-payload from `bstr` to `[ +bstr ]` to carry multiple SUIT Reports
- option 2: Remove suit-reports option from QueryRequest and QueryResponse messages
  - Embedding "boot" time evidence in EAT and set it in attestation-payload option
  - Because **it doesn't match to manifest-list**, and it can be conveyed in attestation-payload option
- option 3: Remain suit-reports option and normative reference
  - Because they match to manifest-list option in Update message

**Comment by dthaler** [comment]
This was discussed in TEEP before, with the main points being:
* When the attestation payload contains Evidence, the attestation payload instead is opaque and goes to the Verifier. 
* The TAM often needs to process the SUIT reports itself, and should not rely on the Verifier copying them into Attestation Reports.

**Comment by kentakayama** [comment]
With `suit-reports` option actually the TAM can easily handle them.
On the other hand, normative reference is too "strong" in my opinion.

**Comment by kentakayama** [comment]
In the interim meeting, we chose option 3. Thanks @dthaler for picking this up.
