### ISSUE TITLE
No reference to each suit-cose-profiles

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#356]
[draft-ietf-suit-mti-02](https://author-tools.ietf.org/iddiff?url1=draft-ietf-suit-mti-01&url2=draft-ietf-suit-mti-02&difftype=--html) has replaced two profiles we depends.

| before -01 => | after -02 |
|--|--|
| suit-sha256-es256-ecdh-a128gcm | suit-sha256-ecdsa-ecdh-a128ctr |
| suit-sha256-eddsa-ecdh-a128gcm | suit-sha256-eddsa-ecdh-a128ctr |

Should we replace each of them?

**Comment by kentakayama** [comment]
@hannestschofenig commented on SUIT ML related to this topic.
The document may re-define `suit-sha256-es256-ecdh-a128gcm` as `[-16, -7, -25, 1]` in the future.

https://mailarchive.ietf.org/arch/msg/suit/UksL5L8CuUAcSpU13LSe1kF13HE/

> Hi all,
>
> I just realized that the SUIT MTI draft needs to create two versions of the profiles, namely one with 
> *	an AEAD cipher for use with regular software, configuration data, personalization data, etc. (as used in TEEP). Some IoT devices will also utilize algorithms from this category. 
> *	Confidentiality-only ciphers. The SUIT MTI draft refers to AES-CTR in the algorithm recommendations. 
> The document must also mention that AES-CTR and AES-CBC have to be used only when needed by the use case described in the firmware encryption draft. AEAD ciphers are the default choice.

**Comment by mingpeiwk** [comment]
Noted a typo in the original description:
"suit-sha256-**ecdsa**-ecdh-a128ctr" should be "suit-sha256-**es256**-ecdh-a128ctr"

**Comment by mingpeiwk** [comment]
@kentakayama Was it a replacement of GCM with CTR or the additional profiles allowed?
