### ISSUE TITLE
*.suit Filename

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/teep-protocol#364]
The examples in Section 4.4 give the impression that there is a registered filename suffix with .suit. I don't believe there is.

**Comment by dthaler** [comment]
They're just examples, and having an extension might be helpful.

**Comment by dthaler** [comment]
@hannestschofenig what are you proposing here?  Remove the .suit suffix?

**Comment by hannestschofenig** [comment]
My proposal is to remove the suffix.

**Comment by dthaler** [comment]
Fixed in draft -17
