### ISSUE TITLE
Evidence opaque to TAM

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/teep-protocol#365]
The following statement is made in Section 8:

"If evidence is not encrypted by the TEEP Agent then it will be opaque to the TEEP Agent and to the TAM."

I would argue that Evidence provided by the TEEP Agent is always opaque to the TAM since it is processed by the Verifier, regardless of whether it is encrypted or not

**Comment by dthaler** [comment]
Fixed in draft -17
