### ISSUE TITLE
Encryption functionality incomplete

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/teep-protocol#367]
There are three places where encryption may be used, namely 
 * SUIT manifest/payload,
 * SUIT Report, and 
 * EAT

draft-ietf-suit-firmware-encryption explains how encryption of the manifest/payload is accomplished.

For SUIT Report and for the EAT a corresponding description is missing. I believe the SUIT Report has to describe how encryption is accomplished for the SUIT Report. For encryption of the EAT, the TEEP protocol has to provide this description. I suggest a new section that copies text from draft-ietf-suit-firmware-encryption (Section 6.2.1, 6.2.3, and 6.2.4).

**Comment by dthaler** [comment]
I believe this is addressed  in #369

**Comment by dthaler** [comment]
Fixed in draft -17
