### ISSUE TITLE
TEEP profile identification

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-teep/teep-protocol#371]
_(For your consideration.)_

In RATS, I suggested using a rfc2648 URN as the value for the `eat_profile` claim (https://github.com/ietf-rats-wg/eat/issues/419).

Laurence has a pending PR to address that  (https://github.com/ietf-rats-wg/eat/pull/420).

The plus is it removes a bunch of bits from the wire, which is rarely a bad thing 😄

**Comment by dthaler** [comment]
Fixed in draft -17
