### ISSUE TITLE
[Hackathon] No selected-suit-cose-profile

### ISSUE THREAD

**Issue by kentakayama** [ietf-teep/teep-protocol#379]
Though the query-request message have `supported-suit-cose-profiles` the query-response does not have `selected-suit-cose-profile` and the teep-error does not have `supported-suit-cose-profiles` as an option.
I think we should define `selected-suit-cose-profile` and add it to query-response, and add `supported-suit-cose-profiles` to teep-error.

**Comment by mcd500** [comment]
I prefer not having different cipher suites selected on the Agent for the TEEP messages and SUIT manifests which would create a requirement for the Agent to have to implement a different algorithm for both TEEP and SUIT portions.
How about merging the two `supported-teep-cipher-suites` and `supported-suit-cose-profiles` and having a suit profile to express which cipher suites to use on both TEEP and SUIT?

**Comment by dthaler** [comment]
> How about merging the two supported-teep-cipher-suites and supported-suit-cose-profiles

I would not try to merge them, though I agree that an Agent would not support both ES256 and EdDsa.  But since the agent gets the pick a suit cose profile and a TEEP cipher suit, I think it's fine to assume the implementer picks intelligently.

> I think we should define selected-suit-cose-profile and add it to query-response

I'd be ok with that, though I'm not sure that it, or the existing selected-teep-cipher-suite is strictly needed, since the messages ought to be self-describing so you should be able to derive it directly.  But if it helps parsing in some implementations (does it?), then I would have no objection.

> I think we should ... add supported-suit-cose-profiles to teep-error.

I had thought that SUIT Reports would handle this.  We don't define a TEEP error code more specific than ERR_MANIFEST_PROCESSING_FAILED since suit-report-result-code should already have the details.  (However the definition of values is missing from the SUIT Report draft it seems, which I just posted to the SUIT list about.)   If the SUIT Report will also list capabilities like supported SUIT COSE profiles, then we don't need to add it to teep-error.   If it won't, then I agree we can add it.

**Comment by kentakayama** [comment]
@dthaler @mcd500 
Thanks for your replies.

This discussion turned my thought to another opinion
- not to create selected-suit-cose-profile (I've changed my mind)
- remove supported-suit-cose-profiles from QueryRequest
- add it to both QueryResponse and Error as optional

It is because the suit-cose-profile does not mean the TAM support it, nor all the manfiests stored in the TAM support them.
For example, one manifest for component A is signed with ES256, and another one for B is signed with EdDSA. Is it appropriate that the TAM set supported-cose-profiles=[ES256, EdDSA]? (The actual value is different though.)
It should not. Suppose that the TAM list them up, and the Agent request the TAM to send a manifest for component A with selected-suit-cose-profile=EdDSA.

Otherwise, it is natural that the TAM does not list it up, and the Agent does it. It actually means that the manifest processor in the Device supports the profile(s).
There is no need the TAM to take care about which algorithm is used in each manifest for each component. It has to care about them only after receiving the QueryResponse message, which contains information about the Agent and the Device and which component should be updated.

**Comment by dthaler** [comment]
The TAM may process SUIT Reports, if doing so helps it determine how to update the device.  SUIT Reports can be encrypted using a suit-cose-profile, so it does make sense for the TAM to report what it understands, hence the field in the QueryRequest.

**Comment by kentakayama** [comment]
@dthaler 
It makes sense. Then the `supported-suit-cose-profiles` in QueryRequest message is still required, that lists the SUIT profiles supported by the TAM to parse SUIT Report. Can we add more description [around here](https://github.com/ietf-teep/teep-protocol/blob/master/draft-ietf-teep-protocol.md?plain=1#L394-L397)?
And then, optional parameter is appropriate I think because [requesting suit-reports is optional](https://github.com/ietf-teep/teep-protocol/blob/master/draft-ietf-teep-protocol.md?plain=1#L357).

Can I add `supported-suit-cose-profiles` to QueryResponse and Error messages that lists the SUIT profiles supported by the Device to parse SUIT Manifest? It must be an optional parameter.

**Comment by dthaler** [comment]
> If the SUIT Report will also list capabilities like supported SUIT COSE profiles, then we don't need to add it to teep-error. If it won't, then I agree we can add it.

Note: we met with Henk (co-author on the SUIT Reports draft) at the end of the Hackathon and he agreed it should be added to SUIT Reports, so not needed in TEEP itself.  That way, it can be used by any other mechanisms that transport SUIT Reports.

**Comment by dthaler** [comment]
Turns out there is a case for adding the supported profiles into the Error message, and that is if there is a failure processing SUIT Reports in the QueryRequest.   Previously there was no text about what the TEEP Agent should do with that field, so I filed PR #382.
