### ISSUE TITLE
SUIT manifest examples

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#41]
Architecture Issue #7 was about implicit SD creation when installing a TA, rather than making it be explicit in the TEEP protocol.  However now the installation of TA’s is done via a SUIT manifest so all the real work is delegated to SUIT.  When a new SD is desired, how should one encode that in a SUIT manifest?

I think we need some examples in the TEEP protocol spec of SUIT commands to install a TA that is 1:1 with an SD (aka no notion of SD), and how to install a TA into an existing SD to enable sharing, etc.

The examples could also be in the SUIT manifest spec instead but that doc is closer to being done hence the suggestion to put in the TEEP protocol spec.

**Comment by dthaler** [comment]
IETF 110 [minutes](https://datatracker.ietf.org/meeting/110/materials/minutes-110-teep-00) say: 

> Issue #41: SUIT manifest example(s); SUIT manifest spec has 6 other examples in Appx B.
> Dave T proposes putting examples in TEEP protocol spec with both manifest and report
> Agreement from: Hannes T, Brendan M, Sorin Faibish.
>
> Possible examples:
> * Manifest: install a TA that needs personalization data
> * Report: partial success
> * Manifest: remove a TA and its dependency
> * Report: full success

**Comment by dthaler** [comment]
Brendan provided https://gitlab.arm.com/research/ietf-suit/suit-tool/-/tree/master/teep-example for use in resolving this issue

**Comment by mcd500** [comment]
Merged the first suit manifest example. https://github.com/ietf-teep/teep-protocol/pull/154
Continue the updating the examples at https://github.com/ietf-teep/teep-protocol/issues/158
