### ISSUE TITLE
Deleting personalization data when deleting a TA

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#42]
The arch spec allows for the TA binary and personalization data to be separate, and even come from different TAMs.  For example, it states:
>    The TEEP protocol treats each TA, any dependencies the TA has, and
>    personalization data as separate components with separate
>    installation steps that are expressed in SUIT manifests, and a SUIT
>    manifest might contain or reference multiple binaries (see
>    [I-D.ietf-suit-manifest] for more details).  The TEEP Agent is
>    responsible for handling any installation steps that need to be
>    performed inside the TEE, such as decryption of private TA binaries
>    or personalization data.

Question is, the TEEP protocol spec has a TrustedAppDelete message that does not use a SUIT manifest, and only has a list of TA's (not "components") to delete.  So it can delete TAs, but how can associated personalization data be deleted, especially when they were installed by different TAMs?

**Comment by dthaler** [comment]
My preferred answer is that the list of "TAs" is actually a list of "components", and anything with a SUIT manifest can be a "component", including personalization data.  With such a clarification, no protocol changes would be needed, just some editorial clarifications in the doc.

**Comment by hannestschofenig** [comment]
I understand why you want to use the term Trusted Component rather than Trusted App in a number of places. If we make this change then I believe we also need to make it in the architecture document. 

Another, less intrusive alternative, is to clarify the term Trusted App. Here is an attempt: 

"
The term Trusted Application in this document refers to a
set of binaries, configuration data, personalization data, or keys expressed in a SUIT manifest, to be installed in
a TEE.  Note that a Trusted Application may include one or more binaries
and/or configuration data and keys needed by a TA to operate correctly.
"

**Comment by dthaler** [comment]
I could live with Hannes's alternative if people have a strong preference.
@mingpeiwk which approach do you prefer?
@mcd500 any opinion?

**Comment by mcd500** [comment]
I really do not mind whether it will be Trusted App or Trusted Component.
Intuitively Trusted App might sound for typical readers only for programing code and not having only personalization data.

**Comment by mingpeiwk** [comment]
I prefer Hannes's suggestion. It saves to modify arch doc, and also is consistent with the common understanding of "Trusted Application". Personalization data is part of Trusted App despite it may be distributed separately.

**Comment by dthaler** [comment]
The problem with Hannes's suggestion now that I read it again is that it says "one or more" binaries, where we need it to be "zero or more" in order to allow for unbundled personalization data as discussed in the arch doc.  I prefer now updating the arch doc and will submit a PR shortly so others can decide.

**Comment by dthaler** [comment]
Fixed in draft-04
