### ISSUE TITLE
Text needed to describe the use of X.509 certificates

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/teep-protocol#44]
Currently, the text in the spec does not talk about the use of X.509 certificates. We should give an example on how this is accomplished with COSE (i.e. it will probably boil down to the use of https://tools.ietf.org/html/draft-ietf-cose-x509-06)

**Comment by dthaler** [comment]
Is this now more for SUIT?

**Comment by dthaler** [comment]
Closing per IETF 109 side meeting discussion
