### ISSUE TITLE
Support for multiple evidence formats

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#48]
As shown in Figure 9 of the [RATS architecture](https://tools.ietf.org/html/draft-ietf-rats-architecture), there are in general multiple evidence formats and multiple attestation result formats.   A design common to a couple companies is to use EAT as the attestation result format, but allow heterogeneous evidence formats, mainly because various ones already exist with currently deployed TEEs.  Thus, the Verifier shown in that figure accepts multiple evidence formats and generates attestation results in one standard format (EAT) that can be used by Relying Parties.   

As shown in Figure 5 of the [TEEP architecture](https://tools.ietf.org/html/draft-ietf-teep-architecture), the TAM is the Relying Party, and evidence is treated as opaque to the TAM, just forwarded on to the Verifier.  As such, there isn't any technical reason the TAM implementation really has to care about the evidence format, only the attestation result format (for which EAT is fine).

As such, the ask is for the TEEP protocol to also be able to work with evidence formats other than EAT.

**Comment by dthaler** [comment]
One piece of this is that some attestation mechanisms either don't have a "nonce" per se (the RATS architecture discusses the use of nonces, or timestamps, or handles), or require a more complex challenge that includes a nonce and other things too.   "nonce" could be renamed to "challenge" for the latter, and made optional for the former.

**Comment by hannestschofenig** [comment]
Your proposed text looks good to me. I am fine with the change of the term "nonce" to "challenge" and also the introduction of alternative attestation formats sounds reasonable. 

I consider this issue closed.

**Comment by dthaler** [comment]
Merging per Hannes's approval.

**Comment by dthaler** [comment]
Fixed in draft-04
