### ISSUE TITLE
Specify RATS claims

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#49]
https://tools.ietf.org/html/draft-ietf-teep-architecture-12#section-7.1 lists claims that need to be specified in order for TEEP to use them.   The proposal is that the TEEP protocol doc be the place to do so.

**Comment by hannestschofenig** [comment]
IMHO these claims already exist in EAT. For example, there are timestamp and nonce claims that cover the freshness requirement. 

Are you suggesting how to use the already available claims for TEEP?

**Comment by dthaler** [comment]
The arch doc lists:
* Device Identifying Information: I think this is the Universal Entity ID Claim (ueid) for identifying the device instance, yes?  But the TEEP arch also says "In some use cases it may be sufficient to identify only the class of the device."  Which EAT claim contains the device class?  The closest thing I see is OEM Identification by IEEE (oemid) but I am not sure that is sufficient since it's only the OEM not the device class from that OEM.
* TEE Identifying Information: Similarly the closest thing I see is Origination Claim (origination) but I am not sure that is sufficient since it's just the manufacturer not the "version identification information such as the hardware, firmware, and software version of the TEE"
* Freshness Proof: Nonce Claim (nonce) in draft-ietf-rats-eat section 3.3
* Requested Components: obsoleted by https://github.com/ietf-teep/architecture/pull/210

The information may be there but it's non-obvious.  Perhaps the best way would be to add an example in the TEEP protocol spec that shows the relevant claims for an EAT from a hypothetical TEE.

**Comment by dthaler** [comment]
This issue is being discussed in the mailing list thread "EAT claims needed by TEEP" that is cross-posted between TEEP and RATS mailing lists.

**Comment by dthaler** [comment]
IETF 109 TEEP notes at https://codimd.ietf.org/notes-ietf-109-teep say

> Conclusion not to use TEEP specific claims.

I.e., belief is that RATS will have generic claims that meet TEEPs requirements above.

**Comment by dthaler** [comment]
https://tools.ietf.org/id/draft-birkholz-rats-suit-claims-01.txt contains proposed claims.  To map them to the remaining TEEP arch requirements:

* Device Identifying Information:  vendor-identifier, class-identifier, and device-identifier claims
* TEE Identifying Information: vendor-identifier, class-identifier, and version claims

**Comment by dthaler** [comment]
Addressed in draft -05
