### ISSUE TITLE
Example of Device has the TA binary and just needs the metadata

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#5]
Feedback from the SECIoT hackathon in Berlin,

We would like to have both scenarios in TEEP protocol in QueryRequest.
(a) The device has the TA binary and just needs the metadata (as for install or delete)
(b) The device needs both the TA binary and the metadata

The current prototype only using (b) at the moment.

This discussion was raised on otrp 
https://github.com/ietf-teep/OTrP/issues/2

**Comment by dthaler** [comment]
Some possible approaches:

Option 1) Treat the "TA binary" as a separate UUID in the ta-list so the TAM can see that it has the TA-binary but not the installed TA.   (This may be seen as overloading a field for something it wasn't meant for so might be confusing.)
Option 2) Put an indicator into the requested-ta-list to indicate that the binary is already available.

**Comment by dthaler** [comment]
See the "have-binary" field in PR #47

**Comment by dthaler** [comment]
Fixed in draft-04

**Comment by mcd500** [comment]
This is related to https://github.com/ietf-teep/teep-protocol/issues/42.
Changes are merged with https://github.com/ietf-teep/teep-protocol/pull/56
Closing it, thanks
