### ISSUE TITLE
Version in QueryRequest

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#50]
The draft currently says:

>    version
>       The version field parameter the version(s) supported by the TAM.
>       For this version of the specification this field can be omitted.

The problem with the last sentence above arises once the version changes.   If the TAM only supports the newer version, it has no way to indicate that the initial version is not supported, since the TEEP Agent as currently implemented will ignore the field and respond expecting the TAM to support the initial version.  At a minimum, text explaining what the expected behavior is, is needed.

**Comment by hannestschofenig** [comment]
The text you added in your commit looks good to me. I consider this issue resolved.
