### ISSUE TITLE
Error Code Registry allocation policy

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#51]
The current draft uses Expert Review, but doesn't contain any rationale for that.   Why do we need to allow vendors to extend error codes?   By comparison HTTP status codes are IETF Review, and both HTTP and the TEEP protocol allow passing a text string along with the error code, which allows vendors to put details into the text string.

I would propose simplifying the TEEP protocol and either 
(a) not using an IANA registry (I.e., require another RFC Updates the current doc), or
(b) using IETF Review like HTTP does

**Comment by hannestschofenig** [comment]
The comparison with HTTP does not seem to be appropriate because TEEP is a specific application protocol. I would like to avoid creating too much standardization effort for extending the protocol later on. That's why I have suggested to allocate error codes based on expert review.

**Comment by dthaler** [comment]
I'd prefer to not allocate new error codes at all.  The analogy with HTTP is that vendors can do customization via the error message not via error codes.   I don't see why a vendor would need a new error code at all.   Extending the protocol via query-request-extensions or teep-option-extensions or query-response-extensions or teep-type-extension requires standardization (nothing in the IANA Considerations section creates registries), right?   I don't see why error codes should be any different.

**Comment by dthaler** [comment]
Addressed in draft -05, need to confirm at IETF 110
