### ISSUE TITLE
SUIT manifest processing errors

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#52]
The TEEP protocol spec currently has error codes for events that would occur as part of parsing and executing a SUIT manifest, including:

>    ERR_TA_UNKNOWN_FORMAT (14)
>       The TEEP Agent returns this error when it does not recognize the
>       format of the TA binary.
> 
>    ERR_TA_DECRYPTION_FAILED (15)
>       The TEEP Agent returns this error when it fails to decrypt the TA
>       binary.
> 
>    ERR_TA_DECOMPRESSION_FAILED (16)
>       The TEEP Agent returns this error when it fails to decompress the
>       TA binary.
> 
>    ERR_MANIFEST_PROCESSING_FAILED (17)
>       The TEEP Agent returns this error when manifest processing
>       failures occur that are less specific than ERR_TA_UNKNOWN_FORMAT,
>       ERR_TA_UNKNOWN_FORMAT, and ERR_TA_DECOMPRESSION_FAILED.

However, section 8.7.4 "Reporting Policy" of draft-ietf-suit-manifest-09 defines a much richer set of record information than can be expressed in such error codes.   I would recommend that such error codes be removed and instead provide a way to report back SUIT_Record information if such info is needed.

**Comment by hannestschofenig** [comment]
I agree that this would be a better design that allows us to keep any future changes to SUIT to be inline with the TEEP protocol mechanism.

**Comment by dthaler** [comment]
Fixed in draft-04
