### ISSUE TITLE
Client APP bound to particular TA

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#6]
Feedback from the SECIoT hackathon in Berlin,

Some client APP which is already installed on Device, require particular TA to work togather.

This is related to "TA Binary in a Client App Installation Implications" 
https://github.com/ietf-teep/architecture/issues/11

With the TA install procedure on page 11 from IETF 105 slides
https://datatracker.ietf.org/meeting/105/materials/slides-105-teep-sessa-teep-architecture-draft

Would like to have a way to specify the TA in QueryResponse message from Device to TAM.

**Comment by dthaler** [comment]
This is a duplicate of issue #2
