### ISSUE TITLE
Construction of Ciphersuites

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#72]
This is current draft.
```
# Ciphersuites {#ciphersuite}

A ciphersuite consists of an AEAD algorithm, an HMAC algorithm, and a signature
algorithm.
Each ciphersuite is identified with an integer value, which corresponds to
an IANA registered
ciphersuite (see {{ciphersuite-registry}}. This document specifies two ciphersuites.
```
```
; ciphersuites as bitmaps
suite = $TEEP-suite .within uint .size 8
```
Is there a reference how the bitmaps of Ciphersuites is constructed in other RFC?

**Comment by mcd500** [comment]
While I was investing this matter, I came across of type in https://tools.ietf.org/html/draft-tschofenig-core-coap-tcp-tls-04.
Just would like to report here.
```

   o  0b000_11000 (24) means an additional 8-bit unsigned Integer is
      appended to the initial length field indicating the total length

   o  0b000_11001 (25) means an additional 16-bit unsigned Integer (in
      network byte order) is appended to the initial length field
      indicating the total length

   o  0b000_11010 (26) means an additional 32-bit unsigned Integer (in
      network byte order) is appended to the initial length field
      indicating the total length
```
The `0b000_11000` `0b000_11001` `0b000_11010` are typo of `0b0001_1000` `0b0001_1001` `0b0001_1010`, since 0b is prefix for binary numbers and typically binary numbers are separated with each 4 bits, so it would match smoothly with hex numbers, in this case, `0x18` `0x19` `0x1a` which matches the description of chart in page 45 of RFC7049 [CBOR].

**Comment by dthaler** [comment]
Fixed in draft -05
