### ISSUE TITLE
Which ciphersuite(s) are mandatory to implement

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-protocol#73]
The current draft defines values for 2 ciphersuites, but is ambiguous as to whether both are mandatory to implement for agents, and whether both are mandatory to implement for TAMs.

**Comment by ko-isobe** [comment]
Two perspectives to consider. One is which cipher suit to add more commonly used in the market to enhance the adaptation and use cases of teep, e.g. adding RSA.
Another is, should not include cipher suit which is already known to be low security.

**Comment by dthaler** [comment]
Fixed in draft -05
