### ISSUE TITLE
Good to have examples of query-request-extensions and teep-option-extensions

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#76]
For improving compatibility among different implementations, good to have examples of `query-request-extensions` and `teep-option-extensions` in messages.

The is definition of Install:

```
install = [
  type: TEEP-TYPE-install,
  token: uint,
  option: {
    ? manifest-list => [ + SUIT_Envelope ],
    * $$install-extensions,
    * $$teep-option-extensions
  }
]
```

**Comment by dthaler** [comment]
Since there are no extensions defined in this version, do we really need examples?

**Comment by mcd500** [comment]
@dthaler I agree, we do not need examples in current draft. Let's wait until when it requires extensions.
