### ISSUE TITLE
teep-message-framework may need update

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#78]
The teep-message-framework in cddl section is not used consistently between query-request and teep-error.
And also current teep-message-framework does not allow having no `options` even it is empty.
We found that it existed from draft 03. https://tools.ietf.org/html/draft-ietf-teep-protocol-03

Description of teep-message-framework in cddl section.
```
teep-message-framework = [
  type: 0..23 / $teep-type-extension,
  token: uint,
  options: { * teep-option },
  * int; further integers, e.g. for data-item-requested
]
```

Description of query-request which matches the teep-message-framework in cddl section by having `data-item-requested` after the `options`.
```
query-request = [
  type: TEEP-TYPE-query-request,
  token: uint,
  options: {
    ? supported-cipher-suites => [ + suite ],
    ? challenge => bstr .size (8..64),
    ? versions => [ + version ],
    ? ocsp-data => bstr,
    * $$query-request-extensions
    * $$teep-option-extensions
  },
  data-item-requested  
]
```

Description of teep-error has `err-code` before the `options`.
```
teep-error = [
  type: TEEP-TYPE-teep-error,
  token: uint,
  err-code: uint,
  options: {
     ? err-msg => text,
     ? supported-cipher-suites => [ + suite ],
     ? versions => [ + version ],
     ? suit-reports => [ + suit-report ],
     * $$teep-error--extensions,
     * $$teep-option-extensions
  }
]
```

I prefer revising the teep-message-framework as following.
```
teep-message-framework = [
  type: 0..23 / $teep-type-extension,
  token: uint,
  * int; further integers, e.g. for data-item-requested
  ? options: { * teep-option },
]
```
Then additional int array-values in any teep messages will be parsed before `options` to make the programmer friendly.
Also options  `options` itself could be deleted from the teep message when entire `options` is empty.

Or alternately:
```
teep-message-framework = [
  type: 0..23 / $teep-type-extension,
  token: uint,
  ? options: { * teep-option },
  * int; further integers, e.g. for data-item-requested
]
```
Keep the additional int array-values after the `options` but still delete the `options` when the `options` is empty.

I would like to have comments and opinion here :)

**Comment by mcd500** [comment]
We discussed it today in Japan for the hackathon, and we would like to keep the format as initial cddl description.
```
teep-message-framework = [
  type: 0..23 / $teep-type-extension,
  token: uint,
  options: { * teep-option },
  * int; further integers, e.g. for data-item-requested
]
```

The reason behind is that always having three entries, `type`, `token` and `options`, in any of teep message, and any other additional entries which might be added becomes after the `options`, will make it easier to matching the teep messages in the implementation.

For the teep message which have empty `options` will have 0xa0 as following:
```
/ teep-success = /
[
    5,          / type : TEEP-TYPE-teep-success = 5 (fixed int) /
    2004318072, / token : 0x777777778 (uint), from Install message /
    / options :  /
    { }
]
```
```
83                        # array(3)
    05                    # unsigned(5)
    1A 77777778           # unsigned(2004318072, 0x77777778)
    A1                   # map(0)
```

This way, it is more consistent among messages.
Though, I have to revise my PR later. https://github.com/ietf-teep/teep-protocol/pull/77

**Comment by dthaler** [comment]
This issue looks like it was caused (at least in part) by PR #64

**Comment by mcd500** [comment]
More details including the relationship of PR https://github.com/ietf-teep/teep-protocol/pull/64
In the draft 03:
https://github.com/ietf-teep/teep-protocol/blob/83d96acbb8d613c100a7584ff8a56a1d945128f8/draft-ietf-teep-protocol.md#error
it was described in the main text as follow:
```
teep-error = [
  type: TEEP-TYPE-teep-error,
  token: uint,
  err-code: uint,
  options: {
     ? err-msg => text,
     ? cipher-suites => [ + suite ],
     ? versions => [ + version ],
     * $$teep-error--extensions,
     * $$teep-option-extensions
  }
]
```
and in the cddl section, it was described as:
```
teep-error = [
  type: TEEP-TYPE-teep-error,
  token: uint,
  options: {
     ? err-msg => text,
     ? cipher-suites => [ + suite ],
     ? versions => [ + version ],
     * $$teep-error--extensions,
     * $$teep-option-extensions
  }
  err-code: uint,
]
```
which I found during the implementation for the hackathon and made the PR https://github.com/ietf-teep/teep-protocol/pull/64,
but later it turns out that,
```
teep-error = [
  type: TEEP-TYPE-teep-error,
  token: uint,
  err-code: uint,
  options: {
     ? err-msg => text,
     ? cipher-suites => [ + suite ],
     ? versions => [ + version ],
     * $$teep-error--extensions,
     * $$teep-option-extensions
  }
]
```
was not complying the with the `teep-message-framework` in the cddl.

For my conclusion, I prefer reverting the changes in the examples of the `teep-error`, and changing both sentence and cddl to match the `teep-message-framework` mentioned above.

**Comment by mcd500** [comment]
This is quick log of discussion at the hackathon on last Friday with Isobe-san, Dave and others.
The idea was to change it to:
```
teep-message-framework = [
  type: 0..23 / $teep-type-extension,
  options: { * teep-option },
  * uint; further integers, e.g. for data-item-requested, token and etc
]
```
Since the `query-request` and `query-response` do not need `token`, so make the `token` optional too.

**Comment by mcd500** [comment]
Quick memo from today's teep side meeting posted by Henk.

Differences of `:` and `=>` in array and map in cddl.
https://tools.ietf.org/html/rfc8610#section-2.1.2

Digest video:
https://www.youtube.com/watch?v=y46dARLUmmI

**Comment by dthaler** [comment]
Addressed in draft -05
