### ISSUE TITLE
Token Management consideration

### ISSUE THREAD

**Issue by ko-isobe** [ietf-teep/teep-protocol#83]
Each TEEP message has `token` field. It has the role of binding TAM and TEEP device.
From some views(e.g. security, implementation),I think it would be preferable to describe how to handle token values.

- How to generate tokens
It is necessary for tokens to have the resistance for avoiding collision and guessing from outsiders.
It's considered in #71 and #40

- Unique token in each TEEP messaging
How should TAM handle in this case?
```
     +------------+           +-------------+
     | TAM        |           |TEEP Agent   |
     +------------+           +-------------+
       QueryRequest ------->
                    <-------   QueryResponse
                    <-------   QueryResponse (contains the above QueryResponse's token)

```
In the current description, both QueryResponse are valid because these responses contain the same valid token.
So TEEP agent can look into TAM's behavior by sending multiple QueryResponse.
I think each TEEP messaging should use the unique token and token validness is once only.

Expanding this consideration for the procedure from QueryRequest/Response to TAInstall/Success, I suggest labeling reusing the same token as SHOULD NOT in the draft. 

- Token using for the other purposes
Token has the role of binding TAM and TEEP devices. TAM may use the tokens as the TEEP procedure's status value in TEEP devices.
Is there any problem with using tokens for that purpose?
Under the circumstances of keeping token uniqueness, I think it's no problem.
But I also think the token's purpose should be limited for binding messaging and using tokens as if device ID SHOULD NOT be good from a security view to avoid unexpected side effects.

- Token expiring
Simplicity, even too much time spent from sending QueryRequest/TAInstall, the token is still valid?
TAM has to manage the TEEP messaging by tokens and generate (unique) tokens.
If the token has an indefinite duration, TAM finally has to manage many tokens.
#43 shows the case that waiting for a certain time to solve dependencies components.
That needs the tokens enough time or indefinite validity.
#71 is also related.

**Comment by mcd500** [comment]
Created PR https://github.com/ietf-teep/teep-protocol/pull/109

**Comment by dthaler** [comment]
To address #40 and this issue, I proposed at IETF 109 to remove the token altogether and use other fields instead.  That discussion is blocked on the resolution of discussion of replay protection in SUIT Reports.  

The [TEEP 109 notes](https://codimd.ietf.org/notes-ietf-109-teep) say:

> Dave: Is token needed for install/delete or can we rely on SUIT report?
> Hannes: The need to associate a request to response because of multiple TEEP Agents.
> Dave to have a follow-up discussion in SUIT WG.

The [SUIT 109 minutes](https://datatracker.ietf.org/meeting/109/materials/minutes-109-suit-00) say:

> DaveT: Refers to an email he posted to the list (see https://mailarchive.ietf.org/arch/msg/suit/dBSWDXWxK0kl21XTw_RpQNyMEf0/). Asking whether SUIT should talk about installing/deleting/updating payloads.
> 
> Brendan: Sees challenges with introducing delete operations. He believe the TEEP use case is orthogonal to the SUIT use case. 
> 
> DaveT: The issue can come up when you install multiple independent components. 
> 
> Brendan: I have to think about this aspect. We need to think about cases where there are multiple copies of a component. 
> 
> DaveT: TEEP has to express the components that are installed and there has to be an identification that there is a need to identify it uniquely.
> We currently do not have the answer but I believe the solution has to go into SUIT.
> 
> Brendan: Will post a mail to the list.

**Comment by dthaler** [comment]
draft-ietf-suit-manifest-12 section 8.7.8 now includes support for deleting components via suit-directive-garbage-collect in a SUIT manifest, so PR #118 removes unneeded-tc-list from the Update list as no longer being needed.

**Comment by dthaler** [comment]
Marking this issue as resolved by the PRs referenced and just leaving issue #40 to track the remaining open issue with tokens

**Comment by dthaler** [comment]
Actually no, PR #110 is discussing this still

**Comment by dthaler** [comment]
Was discussed at IETF 110 (see slides from IETF 110).

Afterwards Göran Selander <goran.selander@ericsson.com> provided the following feedback:

> On the topic of scalability, the nonce in method 2 can be generated based on time in a way that the Receiver only keep a small state, essentially an encryption context. The nonce is the encryption of the current time as measured by the Receiver. (With encryption I suggest authenticated encryption so there is a MAC as well.)
> 
> In practice the crypto also needs an IV, so the receiver in addition to the encryption key would need to store e.g. a fixed number IV_0 and a sequence number SEQ, such that IV = IV_0 + SEQ. For each time a nonce is needed (independent of for which TA) step the sequence number, calculate the IV, encrypt with key and IV, and include SEQ in the nonce.
> 
> When the nonce comes back, extract the SEQ, calculate the IV, decrypt with key and IV (which verifies the MAC), verify the time against its own clock and determine if that if fresh enough (based on the same criteria as would be used in method 1).
> 
> So in comparison with the time stamp based method there is some state needed to be stored. But it is a small state (say 16 bytes each for key, IV_0, SEQ) that doesn't grow with the number of TAs.
