### ISSUE TITLE
Consistancy of tc-list type in TEEP-TYPE-update

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#95]
We have introduced tc-list in TEEP-TYPE-update message after combining messages from Install and Delete.
I would like to change the typo of tc-list in Update message as an arrays of tc-info which would be the same type of tc-list in other messages. This changes will make the implantation simpler when parsing tc-list.

These are the different types of tc-list.
(1) query-response message definition 
```
query-response = [
  type: TEEP-TYPE-query-response,
  options: {
    ? tc-list => [ + tc-info ],
```
(2) update message defination
```
update = [
  type: TEEP-TYPE-update,
  options: {
    ? tc-list => [ + bstr ],
```
(3) update message in cddl section
```
update = [
  type: TEEP-TYPE-update,
  options: {
    ? tc-list => [ + SUIT_Component_Identifier ],
```

My proposal is just changing all of them as the same
```
    ? tc-list => [ + tc-info ],
```

I have created the PR https://github.com/ietf-teep/teep-protocol/pull/94.

@hannestschofenig @dthaler Do you mind considering this changes?

**Comment by mcd500** [comment]
Reflecting the comments from @dthaler at https://github.com/ietf-teep/teep-protocol/pull/91 and https://github.com/ietf-teep/teep-protocol/pull/94.
I have changed them to use `unneeded-tc-list` instead of `tc-list` as bellow, so it will be more obvious that it should contain only tc-list for deleting Trusted Components and it is corresponding to the same name entry in QueryResponse message.
```
update = [
  type: TEEP-TYPE-update,
  options: {
    ? unneeded-tc-list => [ + SUIT_Component_Identifier ],
```

**Comment by mcd500** [comment]
I made the PR for this change https://github.com/ietf-teep/teep-protocol/pull/97.

**Comment by mcd500** [comment]
Adding unneeded-tc-list in Update
https://github.com/ietf-teep/teep-protocol/pull/101

**Comment by mcd500** [comment]
The PR, https://github.com/ietf-teep/teep-protocol/pull/97 and https://github.com/ietf-teep/teep-protocol/pull/101 were merged and fixed in editors copy

**Comment by dthaler** [comment]
Fixed in draft -05
