### ISSUE TITLE
Having Control Operator .size for all entries

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/teep-protocol#99]
I had this in mind for a while but others were always higher priorities.
I would like to propose having Control Operator .size for all entries, or as much as possible, in the draft.
Currently we have .size definition on very a few entries and the size of other entries are unspecified, so it is legitimate for having very large size.
These are the lists which already have .size.
```
version = uint .size 4
data-item-requested = $data-item-requested .within uint .size 8
challenge => bstr .size (8..64),
suite = $TEEP-suite .within uint .size 4
```
For example, this is the CBOR Diagnostic Notation and Binary Representation of QueryRequest Message.
```
/ query-request = /
[
    1,          / type : TEEP-TYPE-query-request = 1 (fixed int) /
    / options : /
    {
        20 : 2004318071, / token : 0x77777777 (uint), generated by TAM /
        1 : [ 1 ], / supported-cipher-suites = 1 (mapkey) : /
                   / TEEP-AES-CCM-16-64-128-HMAC256--256-X25519-EdDSA =
                     [ 1 ] (array of uint .size 8) /
        3 : [ 0 ], / version = 3 (mapkey) : 
                     [ 0 ] (array of uint .size 4) /
        4 : h'010203' / ocsp-data = 4 (mapkey) : 0x010203 (bstr) /
    },
    2           / data-item-requested : trusted-components = 2 (uint) /
]
```
```
83                        # array(3),
   01                     # unsigned(1)
   A4                     # map(4)
      14                  # unsigned(20)
      1A 77777777         # unsigned(2004318071, 0x77777777)
      01                  # unsigned(1)
      81                  # array(1)
         01               # unsigned(1) within .size 8
      03                  # unsigned(3)
      81                  # array(1)
         00               # unsigned(0) within .size 4
      04                  # unsigned(4)
      43                  # bytes(3)
         010203           # "\x01\x02\x03"
   02                     # unsigned(2)
```
Only supported-cipher-suites (.size 8) and version (.size 4) are specified.
If we could specify all the entries with .size, then it will make it possible to predict the total size the query-request message.

Having able to predict the size is important in the implementation especially for the resource constraint iot devices when allocating the buffer size for handling teep messages.
For example, in the line bellow,
```
char *message_buffer;
message_buffer = (char *)malloc(2048);
```
the number of 2048 would not be a just arbitrary number but it could a assure not to overflow from the spec.

Also, this will help preventing from cbor parser to crush by having a large entries in the message.

@hannestschofenig @dthaler if it is OK, I would like to prepare for ietf 110.

**Comment by dthaler** [comment]
I think it's ok so please go ahead, but since some messages can contain manifests and manifests can be large the full message can be larger.

**Comment by mcd500** [comment]
Created the PR for this.
https://github.com/ietf-teep/teep-protocol/pull/108

**Comment by mcd500** [comment]
I had to change the type of token from uint to bstr to support max 64 bytes.
The details are discussed here.
https://mailarchive.ietf.org/arch/msg/teep/fEjx9ck_95iK8BBuop-AOQWjKlw/

**Comment by mcd500** [comment]
The PR was merged https://github.com/ietf-teep/teep-protocol/pull/108

**Comment by dthaler** [comment]
Fixed in draft -05
